.travis.yml
lib/project-utility/ModuleExportTransform.ts
package.json
templates/angular/index.ts
templates/jquery/index.ts
templates/react/index.ts
tsconfig-pack.json

Add npm build and deploy

---

lib/packages/PackageManager.ts
lib/packages/components.ts
lib/templates/AngularTemplate.ts
lib/templates/ReactTemplate.ts
lib/templates/jQueryTemplate.ts
package.json

- Fix missing json config file
- Update descriptions
Closes #50

Npm package updates

---

tsconfig-pack.json

Update tsconfig-pack.json after angular rename

---

package.json

fix(npm): properly package all quickstart files

---

templates/angular/ts/doughnut-chart/default/files/src/app/assets/doughnut-data.ts
templates/angular/ts/doughnut-chart/default/files/src/app/components/__path__/__name__.component.ts
templates/angular/ts/doughnut-chart/default/index.ts
templates/angular/ts/doughnut-chart/index.ts

Adding igDoughnutChart template for Angular

---

templates/angular/ts/funnel-chart/default/files/src/app/assets/funnel-data.ts
templates/angular/ts/funnel-chart/default/files/src/app/components/__path__/__name__.component.ts
templates/angular/ts/funnel-chart/default/index.ts
templates/angular/ts/funnel-chart/index.ts

feat: add funnel chart template for Angular
Closes #25

feat: add funnel chart template for Angular

---

README.md

There were two minor syntax error and I fixed them

fix: correct some syntax errors in README.md

---

lib/PromptSession.ts

feat: Skip prompt question in case there is one theme or none.

---

package.json

chore: rename command to non-dashed `igniteui`

---

lib/project-utility/TypeScriptFileUpdate.ts

feat: add ts transform to import and declare igx identifiers

---

lib/project-utility/TypeScriptFileUpdate.ts

fix: change adding igx module to imports..

---

lib/PromptSession.ts
lib/commands/build.ts
lib/commands/start.ts

feat: start always builds, not just in step by step

---

templates/angular/ig-ts/custom-templates/editors-calculation-form/files/src/app/components/__path__/__name__.component.ts
templates/angular/ig-ts/grid/grid-export/files/src/app/components/__path__/__name__.component.ts
templates/angular/ig-ts/projects/empty/files/package.json
templates/quickstart/angular/app/app.module.ts
templates/quickstart/angular/package.json
templates/quickstart/angular/systemjs.config.js
templates/quickstart/angular/tsconfig.json

update wrappers quickstart to Angular 5 and new-er package

---

templates/angular/ig-ts/projects/empty/files/webpack.config.js

Cannot debug CLI generated application in VS Code

---

templates/react/es6/grid/grid-editing/files/client/components/__path__/index.js
templates/react/es6/hierarchical-grid/hierarchical-grid-custom/files/client/components/__path__/index.js
templates/react/es6/hierarchical-grid/hierarchical-grid-editing/files/client/components/__path__/index.js

This fix is required because of Issue: https://github.com/IgniteUI/ignite-ui/issues/1556

fix: Import 'effect-blind'

---

package.json

This was added with PR #149 (#67)

Include new defaults.json config in package output

---

templates/angular/ig-ts/projects/empty/files/.gitignore
templates/angular/ig-ts/projects/empty/files/src/.gitignore
templates/jquery/js/projects/empty/files/.gitignore
templates/react/es6/projects/empty/files/.gitignore

… and modify Angular one.
#122

Add initial .gitignore files for jQuery and React projects

---

README.md

#175 Changing the port

---

package.json

update package.json to include .gitignore in all empty projects

---

lib/PromptSession.ts
lib/Util.ts
lib/cli.ts
lib/commands/add.ts
lib/commands/new.ts
spec/unit/new-spec.ts

Applying some formatting/wording changes based on feedback from @sbozalieva

Step by step question / info messages updates

---

.travis.yml

#122
Also add a build variable to change npm release tag from `latest` to `next` for beta versions.

Update CI npm to correctly pack `.gitignore` files

---

lib/PromptSession.ts
lib/Util.ts
lib/commands/new.ts
lib/config/defaults.json
lib/types/Config.d.ts
spec/acceptance/new-spec.ts
spec/unit/new-spec.ts

Add skipGit configuration option

---

.gitignore
lib/ProjectConfig.ts
lib/commands/config.ts
package-lock.json
package.json
spec/unit/config-spec.ts

feat: add validation for configuration options in config set command

---

templates/angular/igx-ts/list/default/files/src/app/__path__/__name__.component.html

chore: typo in the igx-list template

---

templates/angular/ig-ts/projects/empty/files/package.json

Add ts-node package so ig-ts Karma test can run.

fix: Add ts-node package

---

templates/angular/igx-ts/projects/empty/files/package.json
templates/angular/igx-ts/tabbar/default/files/src/app/__path__/__name__.component.html
templates/angular/igx-ts/tabbar/default/index.ts
templates/angular/igx-ts/tabbar/index.ts

Tpaskalev/update cli 5.3.0

---

lib/Util.ts
lib/commands/add.ts
lib/commands/build.ts
lib/packages/PackageManager.ts
lib/templates/AngularTemplate.ts
lib/templates/ReactTemplate.ts
lib/templates/jQueryTemplate.ts
lib/types/Template.d.ts
spec/acceptance/generate-spec.ts
spec/unit/add-spec.ts
spec/unit/packageManager-spec.ts
templates/angular/ig-ts/generate/template.json
templates/angular/igx-ts/generate/template.json
templates/jquery/js/generate/template.json
templates/react/es6/generate/template.json

Add npm package dependencies support for templates

---

templates/angular/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__name__.component.spec.ts
templates/angular/igx-ts/list/default/files/src/app/__path__/__name__.component.spec.ts
templates/angular/igx-ts/tabbar/default/files/src/app/__path__/__name__.component.spec.ts

fix: Fix igx tests failures caused by modules renaming.

---

templates/angular/igx-ts/time-picker/default/files/src/app/__path__/__name__.component.html
templates/angular/igx-ts/time-picker/default/files/src/app/__path__/__name__.component.spec.ts
templates/angular/igx-ts/time-picker/default/files/src/app/__path__/__name__.component.ts
templates/angular/igx-ts/time-picker/default/index.ts
templates/angular/igx-ts/time-picker/index.ts

feat: Add sample time-picker with initial value

---

templates/angular/igx-ts/projects/empty/files/package.json

feat: Use latest released version.

---

package-lock.json
package.json
templates/angular/igx-ts/index.ts

Update inquier version to 6.0.0

---

.travis.yml
templates/angular/igx-ts/category-chart/default/index.ts
templates/angular/igx-ts/financial-chart/default/index.ts

Update charts package version and add new dependency

---

templates/angular/ig-ts/projects/empty/index.ts

Updating the project description

---

templates/angular/igx-ts/carousel/default/files/src/app/__path__/__name__.component.html
templates/angular/igx-ts/combo/default/files/src/app/__path__/__name__.component.html
templates/angular/igx-ts/date-picker/default/files/src/app/__path__/__name__.component.html
templates/angular/igx-ts/grid/default/files/src/app/__path__/__name__.component.html
templates/angular/igx-ts/grid/grid-custom/files/src/app/__path__/__name__.component.html
templates/angular/igx-ts/list/default/files/src/app/__path__/__name__.component.html
templates/angular/igx-ts/tabbar/default/files/src/app/__path__/__name__.component.html
templates/angular/igx-ts/time-picker/default/files/src/app/__path__/__name__.component.html

Angular - Templates - Update ReadMe and add documentation link

---

templates/angular/igx-ts/projects/empty/files/e2e/src/app.e2e-spec.ts
templates/angular/igx-ts/projects/empty/files/src/app/home/home.component.ts

Home view Ignite UI for Angular typo

---

lib/PromptSession.ts
lib/Util.ts
spec/unit/PromptSession-spec.ts
spec/unit/Util-spec.ts
spec/unit/cli-spec.ts
templates/jquery/js/custom-templates/editors-calculation-form/index.ts

Closes #215  .  
Closes #216  .
Additional information:
After these changes default **app**, **component** and **view** names being suggested during an user interaction in a Prompt Session will be incremented based on the already generated project folder structure.

Increment default names suggested, based on existing folders

---

templates/angular/igx-ts/grid/grid-custom/files/src/app/__path__/__name__.component.html
templates/angular/igx-ts/grid/grid-custom/index.ts

Enabled features in the IgxGrid custom template will now be listed as links and lead to the resp. feature's documentation page.

Templates - Angular - Add links to feature docs on custom IgxGrid template

---

lib/BaseProjectLibrary.ts
lib/PromptSession.ts
lib/TemplateManager.ts
lib/types/ComponentGroup.d.ts
lib/types/ProjectLibrary.d.ts
package.json
spec/helpers/mocks.ts
spec/unit/BaseProjectLibrary-spec.ts
spec/unit/PromptSession-spec.ts
spec/unit/TemplateManager-spec.ts
templates/angular/ig-ts/index.ts
templates/angular/igx-ts/groups.json
templates/angular/igx-ts/index.ts
templates/jquery/js/groups.json
templates/jquery/js/index.ts
templates/react/es6/index.ts

feat: add a ComponentGroup interface to describe groups in step by step

---

templates/angular/igx-ts/input-group/default/files/src/app/__path__/__name__.component.css
templates/angular/igx-ts/input-group/default/files/src/app/__path__/__name__.component.html
templates/angular/igx-ts/input-group/default/files/src/app/__path__/__name__.component.spec.ts
templates/angular/igx-ts/input-group/default/files/src/app/__path__/__name__.component.ts
templates/angular/igx-ts/input-group/default/index.ts
templates/angular/igx-ts/input-group/index.ts

Form view template

---

templates/angular/ig-ts/hierarchical-grid/index.ts
templates/angular/igx-ts/groups.json
templates/angular/igx-ts/projects/empty/files/ignite-ui-cli.json
templates/jquery/js/hierarchical-grid/index.ts
templates/jquery/js/projects/empty/files/ignite-ui-cli.json
templates/react/es6/hierarchical-grid/index.ts
templates/react/es6/projects/empty/files/ignite-ui-cli.json

Add missing Angular igx-ts group descriptions.

---

templates/angular/igx-ts/projects/empty/files/src/polyfills.ts

fix: Add es7/object in polyfill.ts

---

lib/PromptSession.ts

fix(*): proper chalk import

---

lib/commands/quickstart.ts
lib/commands/start.ts

Related to npm change made in https://github.com/IgniteUI/igniteui-cli/pull/394

Properly resolve lite-server/browser-sync from projects

---

templates/angular/igx-ts/grid/grid-custom/files/src/app/__path__/__name__.component.html
templates/angular/igx-ts/grid/grid-custom/files/src/app/__path__/__name__.component.ts
templates/angular/igx-ts/grid/grid-custom/index.ts
templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/login/login.component.html

Remove obsolete date picker workaround and reduce description paragraphs.

Update Custom Grid template

---

lib/ProjectConfig.ts
migrations/migration-collection.json
migrations/update-3/index.spec.ts
migrations/update-3/index.ts
templates/angular/ig-ts/projects/empty/files/ignite-ui-cli.json
templates/angular/igx-ts/projects/_base/files/ignite-ui-cli.json
templates/jquery/js/projects/empty/files/ignite-ui-cli.json
templates/quickstart/angular/ignite-ui-cli.json
templates/react/es6/projects/empty/files/ignite-ui-cli.json

Set version in all proj configs, migrate igx project template

---

lib/GoogleAnalytics.ts
spec/unit/GoogleAnalytic-spec.ts

Related to this thread: https://www.infragistics.com/community/forums/f/ignite-ui-for-angular/119203/cant-get-started

fix(npm): generate random guid if needed

---

templates/angular/ig-ts/projects/empty/files/package.json

Update to Angular7 & igniteui-angular-wrappers to v7

---

templates/jquery/js/projects/empty/files/package.json
templates/react/es6/projects/empty/files/package.json

Updating IgniteUI for JavaScript packages to 18.2

---

lib/project-utility/TypeScriptFileUpdate.ts
lib/project-utility/TypeScriptUtils.ts
package-lock.json
package.json
schematics/cli-config/index.spec.ts
schematics/cli-config/index.ts
schematics/tslint.json
spec/unit/ts-transform/TypeScriptFileUpdate-spec.ts
spec/unit/ts-transform/TypeScriptUtils-spec.ts
tslint.json

- Added IFileSystem as a unified base for fs and Angular API file management
- Added NgTreeFileSystem to handle Angular's tree file management
- Added FsFileSystem to handle file management that goes through fs
- Updated TypeScriptFileUpdate
- Refactored the schematic's implementation and specs
- Updated packages' versions

cli-config schematic refactoring

---

lib/commands/add.ts
lib/templates/AngularTemplate.ts
lib/templates/IgniteUIForAngularTemplate.ts
lib/templates/ReactTemplate.ts
lib/templates/jQueryTemplate.ts
lib/types/Template.d.ts
lib/types/TemplateArgs.d.ts
spec/unit/add-spec.ts
spec/unit/base-templates/AngularTemplate-spec.ts
spec/unit/base-templates/IgniteUIForAngularTemplate-spec.ts

New add command --skip-route argument #368

---

templates/angular/igx-ts/projects/_base/files/package.json
templates/angular/igx-ts/projects/side-nav-auth/files/package.json

Update igx-ts projects to use igniteui-angular 7.1.0-beta.2

Update igx-ts projects to use igniteui-angular 7.1.0-beta.2

---

lib/templates/IgniteUIForAngularTemplate.ts
templates/angular/igx-ts/grid/grid-batch-editing/files/src/app/__path__/__name__.component.html
templates/angular/igx-ts/grid/grid-batch-editing/files/src/app/__path__/grid-transaction.component.ts
templates/angular/igx-ts/grid/grid-batch-editing/index.ts

fix(igx-ts): Batch editing template relative dep path

---

lib/PromptSession.ts
lib/config/defaults.json
lib/types/Config.d.ts
package-lock.json
package.json
spec/acceptance/add-spec.ts
spec/acceptance/config-spec.ts
spec/acceptance/new-spec.ts
spec/unit/PromptSession-spec.ts

Step by step mode: Skip framework/project type selectiion with config

---

templates/angular/igx-ts/projects/_base/files/package.json
templates/angular/igx-ts/projects/_base/files/src/polyfills.ts
templates/angular/igx-ts/projects/_base/files/tslint.json
templates/angular/igx-ts/projects/side-nav-auth/files/package.json

Update Ignite UI for Angular templates to latest 7.1.0 release and ng cli latest

---

migrations/migration-collection.json
migrations/update-3_2/index.spec.ts
migrations/update-3_2/index.ts

Attempt to migrate summaries operand change

---

templates/angular/igx-ts/projects/empty/files/package.json

chore: Update default project ignteui-angular package to 6.x.х

---

templates/angular/igx-ts/combo/default/files/src/app/__path__/__name__.component.html

Closes #431 
Update combo view to use proper template selectors

Update Combo view to use template directives

---

templates/angular/igx-ts/custom-templates/crm-grid/files/src/app/__path__/__name__.component.scss

Update crm grid template to use correct style mixin

---

templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/auth.guard.spec.ts
templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/login-bar/login-bar.component.spec.ts
templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/login/login.component.spec.ts
templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/providers/facebook-provider.ts
templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/providers/providers.spec.ts
templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/register/register.component.spec.ts
templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/authentication.service.ts
templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/jwt-util.ts
templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/jwt.spec.ts
templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/services.spec.ts

test(auth-module): add tests for authentication module project

---

schematics/cli-config/index.spec.ts
schematics/utils/theme-import.ts

Add default styles to angular workspace for sass projects

---

lib/Util.ts
lib/commands/start.ts
spec/unit/start-spec.ts
templates/react/igr-es6/bullet-graph/default/files/src/views/__path__/index.js
templates/react/igr-es6/bullet-graph/default/index.ts
templates/react/igr-es6/category-chart/default/index.ts
templates/react/igr-es6/doughnut-chart/default/index.ts
templates/react/igr-es6/financial-chart/default/index.ts
templates/react/igr-es6/grid/basic/index.ts
templates/react/igr-es6/index.ts
templates/react/igr-es6/linear-gauge/default/index.ts
templates/react/igr-es6/pie-chart/default/index.ts
templates/react/igr-es6/projects/_base/files/ignite-ui-cli.json
templates/react/igr-es6/projects/_base/files/package.json
templates/react/igr-es6/projects/_base/files/public/index.html
templates/react/igr-es6/projects/_base/index.ts
templates/react/igr-es6/projects/top-nav/index.ts
templates/react/igr-es6/radial-gauge/default/index.ts

* Minor template updates and cleanup, bumped version to latest CRA
* Proper name increment when suggesting template names
* Added post changing support with `ig start`, default port to 3003. Coverage.

Ignite UI for React project support updates

---

templates/react/igr-es6/projects/_base/files/README.md
templates/react/index.ts

Additional information related to this pull request

Update Ignite UI for React project readme

---

templates/react/igr-es6/bullet-graph/default/files/src/views/__path__/test.js
templates/react/igr-es6/category-chart/default/files/src/views/__path__/test.js
templates/react/igr-es6/doughnut-chart/default/files/src/views/__path__/test.js
templates/react/igr-es6/financial-chart/default/files/src/views/__path__/test.js
templates/react/igr-es6/grid/basic/files/src/views/__path__/test.js
templates/react/igr-es6/linear-gauge/default/files/src/views/__path__/test.js
templates/react/igr-es6/pie-chart/default/files/src/views/__path__/test.js
templates/react/igr-es6/projects/_base/files/package.json
templates/react/igr-es6/projects/top-nav/files/src/setupTests.js
templates/react/igr-es6/radial-gauge/default/files/src/views/__path__/test.js

feat(igr-es6): add enzyme + adapter package, support tests on template

---

.vscode/launch.json
lib/commands/new.ts
spec/acceptance/help-spec.ts
spec/acceptance/new-spec.ts
spec/unit/new-spec.ts

New command: install packages on creation, add `--skip-install` param

---

templates/react/igr-es6/linear-gauge/default/index.ts
templates/react/igr-es6/radial-gauge/default/index.ts

fix(igr-templates): change linear and radial gauge template ids, #459

---

templates/angular/igx-ts/date-picker/default/files/src/app/__path__/__name__.component.html

Update igxDatePicker template

---

templates/angular/igx-ts/projects/_base/files/package.json
templates/angular/igx-ts/projects/side-nav-auth/files/package.json

Update projects to use latest beta

---

templates/angular/igx-ts/grid/default/files/src/app/__path__/__name__.component.html
templates/angular/igx-ts/grid/grid-batch-editing/files/src/app/__path__/__name__.component.html
templates/angular/igx-ts/grid/grid-custom/files/src/app/__path__/__name__.component.html
templates/angular/igx-ts/grid/grid-summaries/files/src/app/__path__/__name__.component.html
templates/angular/igx-ts/grid/multi-column-headers/files/src/app/__path__/__name__.component.html

update links to readme doc in grid templates

---

templates/angular/igx-ts/projects/_base/files/package.json
templates/angular/igx-ts/projects/side-nav-auth/files/package.json

Update CLI to use latest igniteui for angular rc

---

templates/angular/igx-ts/projects/_base/files/package.json
templates/angular/igx-ts/projects/side-nav-auth/files/package.json

update igniteui-angular to latest RC-2

---

templates/angular/igx-ts/projects/_base/files/package.json
templates/angular/igx-ts/projects/side-nav-auth/files/package.json

Update all igx-ts projects to use Ignite UI for Angular Release Candidate 3

Update projects to latest RC3

---

templates/angular/igx-ts/projects/_base/files/package.json
templates/angular/igx-ts/projects/side-nav-auth/files/package.json

Update igntieui-angular to latest RC

---

templates/angular/igx-ts/custom-templates/login/files/src/app/__path__/__name__.component.scss
templates/angular/igx-ts/custom-templates/login/files/src/app/__path__/__name__.component.spec.ts
templates/angular/igx-ts/custom-templates/login/files/src/app/__path__/__name__.component.ts

fix(igx-ts): login view scenario is properly templated

---

templates/angular/igx-ts/projects/_base/files/package.json
templates/angular/igx-ts/projects/side-nav-auth/files/package.json

Angular - Update igniteui-angular version to 7.3.0 beta

---

templates/angular/igx-ts/projects/_base/files/package.json
templates/angular/igx-ts/projects/side-nav-auth/files/package.json

chore(igx-ts): bump igniteui-angular version to 7.3.0-beta.1

---

templates/angular/igx-ts/projects/_base/files/package.json
templates/angular/igx-ts/projects/side-nav-auth/files/package.json

chore(igx-ts): bump igniteui-angular version to 7.3.0-rc.1

---

templates/angular/igx-ts/dialog/default/index.ts

fix(angular): add `IgxButtonModule` import to dialog template

---

templates/angular/igx-ts/projects/empty-page/files/src/app/app.component.html
templates/angular/igx-ts/projects/empty-page/files/src/app/app.component.scss
templates/angular/igx-ts/projects/empty-page/files/src/app/home/home.component.scss

Add samples container for empty project

---

templates/angular/igx-ts/hierarchical-grid/hierarchical-grid-custom/files/src/app/__path__/__name__.component.html
templates/angular/igx-ts/hierarchical-grid/hierarchical-grid-custom/index.ts

Properly pass in column reference on column pinning

---

templates/angular/igx-ts/projects/_base/files/package.json
templates/angular/igx-ts/projects/side-nav-auth/files/package.json

Updating igniteui-angular to 7.3.0

---

templates/angular/igx-ts/hierarchical-grid/hierarchical-grid-custom/files/src/app/__path__/__name__.component.ts
templates/angular/igx-ts/hierarchical-grid/hierarchical-grid-custom/index.ts

Stop event propagation on pin icon click

---

templates/angular/igx-ts/select/default/files/src/app/__path__/__name__.component.scss
templates/angular/igx-ts/select/select-groups/files/src/app/__path__/__name__.component.scss

Update samples styles

---

lib/Util.ts

Refactor `processTemplates` to no be recursive and use a lot less code

refactor(templates): simplify processTemplates

---

lib/PromptSession.ts
lib/Util.ts
lib/commands/add.ts
spec/unit/PromptSession-spec.ts
spec/unit/add-spec.ts

Closes # .  
Reduced the number of while loops - simple task queue with back option
and making use of inquirer's validate functionality.

refactor(step-by-step): rework choose action loop with tasks, validation

---

package-lock.json
package.json

fix(npm): restrict inquirer version due to terminal freeze in latest pkg

---

templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/authentication-routing.module.ts
templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/login/login.component.ts
templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/providers/base-oidc-provider.ts
templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/providers/facebook-provider.ts
templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/redirect/redirect.component.ts
templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/external-auth-configs.ts
templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/external-auth.service.ts

Interface change related to https://github.com/angular/angular-cli/issues/14876

Change ExternalAuthConfig to abstract class; fix circular dependencies

---

package-lock.json
package.json
templates/angular/igx-ts/projects/_base/files/package.json
templates/angular/igx-ts/projects/side-nav-auth/files/package.json

Versions contain fixes for the issues we had - [inquirer](https://github.com/SBoudrias/Inquirer.js/issues/811#issuecomment-504345286), [web-animations-js](https://github.com/web-animations/web-animations-js/pull/208#issuecomment-505348519)

fix(*): update inquirer & web-animations-js package versions

---

templates/angular/igx-ts/grid/grid-batch-editing/files/src/app/__path__/__name__.component.spec.ts
templates/angular/igx-ts/projects/_base/files/angular.json
templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/login/login.component.spec.ts
templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/providers/providers.spec.ts
templates/angular/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/services.spec.ts

Currently, tests will not run on an igx-ts generated project because the `tsconfig` location is not properly configured in `angular.json`
**THIS PR DEPENDS ON #524**
Also fixes some tests, so `npm run test` can actually... test.

 fix(igx-auth-proj): fix tests in igx-auth-proj, fix tsconfig location in angular.json

---

package-lock.json
package.json

Remove igniteui-angular from dependencies

---

templates/angular/igx-ts/bullet-graph/default/index.ts
templates/angular/igx-ts/category-chart/default/index.ts
templates/angular/igx-ts/financial-chart/default/index.ts
templates/angular/igx-ts/linear-gauge/default/index.ts
templates/angular/igx-ts/radial-gauge/default/index.ts

Change dependencies from beta to latest release

---

migrations/migration-collection.json
migrations/update-4_2_3/index.spec.ts
migrations/update-4_2_3/index.ts

chore(migration): Awesome Grid extra paginator style for 4.2.3

---

templates/angular/igx-ts/projects/_base/files/package.json
templates/angular/igx-ts/projects/side-nav-auth/files/package.json

Bump cli version to 8.2.0-rc.0

---

templates/angular/igx-ts/custom-templates/fintech-grid/files/src/app/__path__/__name__.component.spec.ts
templates/angular/igx-ts/projects/_base/files/package.json
templates/angular/igx-ts/projects/side-nav-auth/files/package.json

chore(*): add package 8.2.0 version

---

package.json
spec/jasmine-runner.ts

Update paths to files that should be checked for coverage (in package.json)
Update path to schematics + migrations spec files (in jasmine-runner.ts)

test(coverage): include files for coverage, update path to schematic specs

---

templates/angular/igx-ts/list/default/files/src/app/__path__/__name__.component.scss

fix(igx-templates): add padding to list component template

---

CHANGELOG.md
packages/cli/package.json
packages/core/package.json
packages/igx-templates/package.json
packages/ng-schematics/package.json

release: 5.0.0-alpha.3

---

schematics/utils/theme-import.ts
spec/unit/PromptSession-spec.ts
templates/angular/igx-ts/projects/_base/files/src/styles.scss
templates/angular/igx-ts/projects/_base/index.ts

Closes #572, https://github.com/IgniteUI/igniteui-angular/issues/3968

Аdd autoprefixer grid: on alongside the custom theme

---

CHANGELOG.md
packages/cli/package.json
packages/core/package.json
packages/igx-templates/package.json
packages/ng-schematics/package.json

release: 5.0.0-beta.0

---

packages/cli/lib/PromptSession.ts
packages/cli/lib/commands/add.ts
packages/cli/lib/commands/new.ts

Add messages prompting the user to try cli schematics out

---

packages/igx-templates/igx-ts/autocomplete/autocomplete-custom/index.ts
packages/igx-templates/igx-ts/autocomplete/autocomplete-extended/index.ts

fix(igx-ts): update autocomplete templates to import FormsModule

---

schematics/cli-config/index.spec.ts
schematics/cli-config/index.ts
schematics/utils/theme-import.ts

fix(schematics): use project config instead of hard-coded paths

---

packages/igx-templates/igx-ts/projects/side-nav-auth/files/tsconfig.app.json

fix(igx-templates): fix side-auth template tsconfig.app.json, #

---

CHANGELOG.md
packages/cli/package.json
packages/core/package.json
packages/igx-templates/package.json
packages/ng-schematics/package.json

release: 5.0.0-beta.2

---

packages/ng-schematics/src/ng-new/index.ts
packages/ng-schematics/src/ng-new/index_spec.ts

fix(new, schematics): No prompts when "name" is provided

---

packages/igx-templates/igx-ts/autocomplete/autocomplete-extended/index.ts
packages/igx-templates/igx-ts/hierarchical-grid/hierarchical-grid-custom/index.ts
packages/igx-templates/igx-ts/list/default/files/src/app/__path__/__filePrefix__.component.scss
packages/igx-templates/igx-ts/projects/_base/files/src/styles.scss
packages/igx-templates/igx-ts/projects/_base/index.ts
packages/ng-schematics/src/utils/theme-import.ts
spec/unit/PromptSession-spec.ts

Merge master into vNext

---

CHANGELOG.md
packages/cli/package.json
packages/core/package.json
packages/igx-templates/package.json
packages/ng-schematics/package.json

release: 5.0.0-beta.3

---

packages/igx-templates/IgniteUIForAngularTemplate.ts
packages/igx-templates/igx-ts/hierarchical-grid/hierarchical-grid-custom/index.ts
spec/unit/base-templates/IgniteUIForAngularTemplate-spec.ts

fix(ig-add): only take into account 'extraConfig' in generateConfig

---

templates/angular/igx-ts/grid/grid-batch-editing/files/src/app/__path__/__name__.component.html

Disable button on delete

---

lib/commands/new.ts

Closes #608  .  
Test with ig new and with the schematics.

Create new project when no name but theme is provided

---

spec/unit/packageManager-spec.ts
templates/angular/ig-ts/projects/empty/files/package.json
templates/jquery/js/projects/empty/files/package.json
templates/quickstart/angular/package.json
templates/quickstart/jquery/index.html
templates/quickstart/react/package.json
templates/react/es6/projects/empty/files/package.json

Update ignite-ui package to v19.2

---

.vscode/launch.json

Adding config setup so it is now possible to add new _ig-ts_ empty project and later add a combo to this project via View/Debug --> _Launch New Angular ig-ts_ // _Add Combo to Angular ig-ts_

Update vscode launch config

---

templates/angular/igx-ts/chip/default/files/src/app/__path__/__name__.component.html

Fix chip template

---

templates/angular/ig-ts/projects/empty/files/karma-test-entry.ts

Importing 'rxjs' in karma-test-entry

---

packages/igx-templates/igx-ts/custom-templates/crm-grid/index.ts

fix(templates, igx): add chart packages #679

---

packages/igx-templates/igx-ts/custom-templates/awesome-grid/index.ts

fix(templates, igx): add chart packages #684

---

packages/igx-templates/igx-ts/projects/_base/files/package.json
packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json

Closes # .  
Related https://github.com/angular/angular-cli/issues/16017

chore(igx-ts): project template package.json update

---

package.json
packages/cli/package.json
packages/core/package.json
packages/core/util/GoogleAnalytics.ts
packages/igx-templates/package.json
packages/ng-schematics/package.json
packages/ng-schematics/src/ng-new/index_spec.ts
spec/acceptance/help-spec.ts
spec/acceptance/new-spec.ts
spec/unit/TemplateManager-spec.ts
yarn.lock

yarn upgrade-interactive [--latest]
yarn workspace @igniteui/angular-schematics upgrade rxjs@6.5.3 --exact
yarn workspace igniteui-cli add rxjs@6.5.3 --exact --dev
Closes #690  .  

Schematics dep updates

---

packages/ng-schematics/src/component/index.ts

fix(schematics): ensure component prompt installs packages #695

---

CHANGELOG.md

docs(changelog): transfer over old changelog and preliminary 5.0.0 notes

---

packages/cli/lib/commands/start.ts
packages/core/util/Util.ts
spec/unit/start-spec.ts

fix(start): inherit all stdio, not just input #699

---

packages/cli/templates/angular/ig-ts/custom-templates/tree-grid-file-explorer/index.ts
packages/cli/templates/angular/ig-ts/grid/basic/index.ts
packages/cli/templates/angular/ig-ts/grid/grid-custom/index.ts
packages/cli/templates/angular/ig-ts/grid/grid-editing/index.ts
packages/cli/templates/angular/ig-ts/grid/grid-export/index.ts
packages/cli/templates/angular/ig-ts/grid/grid-templating/index.ts
packages/cli/templates/angular/ig-ts/hierarchical-grid/hierarchical-grid-custom/index.ts
packages/cli/templates/angular/ig-ts/hierarchical-grid/hierarchical-grid-editing/index.ts
packages/cli/templates/angular/ig-ts/hierarchical-grid/hierarchical-grid-export/index.ts
packages/cli/templates/angular/ig-ts/hierarchical-grid/hierarchical-grid/index.ts

fix(ig-ts): correct grid features template variable #702

---

packages/igx-templates/igx-ts/bullet-graph/default/index.ts
packages/igx-templates/igx-ts/category-chart/default/index.ts
packages/igx-templates/igx-ts/custom-templates/awesome-grid/index.ts
packages/igx-templates/igx-ts/custom-templates/crm-grid/index.ts
packages/igx-templates/igx-ts/custom-templates/fintech-grid/index.ts
packages/igx-templates/igx-ts/financial-chart/default/index.ts
packages/igx-templates/igx-ts/linear-gauge/default/index.ts
packages/igx-templates/igx-ts/radial-gauge/default/index.ts

Updating the versions of igniteui-angular-core, gauges and charts

---

packages/cli/migrations/migration-collection.json
packages/cli/migrations/update-5_0_3/index.spec.ts
packages/cli/migrations/update-5_0_3/index.ts
packages/igx-templates/igx-ts/projects/_base/files/src/app/error-routing/error-routing.module.ts
packages/igx-templates/igx-ts/projects/_base/files/src/app/error-routing/error/global-error-handler.service.ts

Angular proj template error handler log instead throw, register only in prod

---

packages/cli/package.json
packages/igx-templates/index.ts
packages/igx-templates/package-resolve.spec.ts
packages/igx-templates/package-resolve.ts
packages/ng-schematics/src/cli-config/index.ts
packages/ng-schematics/src/cli-config/index_spec.ts
packages/ng-schematics/src/utils/theme-import.ts
spec/jasmine-runner.ts

Schematics resolve library package from project

---

packages/cli/lib/commands/upgrade.ts
spec/unit/upgrade-spec.ts

Make update command prompts more meaningful

---

packages/cli/lib/PromptSession.ts
packages/cli/lib/commands/add.ts
packages/core/prompt/BasePromptSession.ts
packages/igx-templates/Update.spec.ts
packages/igx-templates/Update.ts
packages/igx-templates/igx-ts/projects/_base/files/package.json
packages/igx-templates/igx-ts/projects/_base/index.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json
packages/ng-schematics/src/ng-new/index.ts
packages/ng-schematics/src/ng-new/index_spec.ts
packages/ng-schematics/src/prompt/SchematicsPromptSession.ts
packages/ng-schematics/src/upgrade-packages/index.spec.ts
packages/ng-schematics/src/upgrade-packages/index.ts
packages/ng-schematics/src/upgrade-packages/schema.json
spec/unit/PromptSession-spec.ts

Now in wizard we will ask if user will use paid package. If so update the `package.json`.
Closes #724 

Add question to update to paid package for angular

---

packages/igx-templates/Update.spec.ts
packages/igx-templates/Update.ts
packages/igx-templates/package-resolve.ts

Closes #741.  
Handle upgrading imports and dependencies to multiple packages w/ trial and licensed definitions.

feat(upgrade): handle multiple licensed packages

---

packages/ng-schematics/src/SchematicsTemplateManager.ts
packages/ng-schematics/src/collection.json

Minor schematics fixes

---

packages/core/packages/PackageManager.ts

Related #748.  
Magic, do not touch.

fix(upgrade): clear stdin stream before login prompt

---

packages/igx-templates/Update.spec.ts
packages/igx-templates/Update.ts

fix(igx,upgrade): ignore projects without sourceRoot

---

packages/igx-templates/IgniteUIForAngularTemplate.ts
packages/igx-templates/Update.spec.ts
packages/igx-templates/Update.ts
packages/igx-templates/package-resolve.spec.ts
packages/igx-templates/package-resolve.ts
packages/ng-schematics/src/cli-config/index.ts
packages/ng-schematics/src/utils/theme-import.ts

Closes #741.  
Add separate package definition used for packages w/ licensed and trial definitions.

refactor(upgrade): handle multiple licensed packages, #741

---

README.md
packages/cli/templates/angular/ig-ts/projects/empty/files/package.json
packages/cli/templates/jquery/js/generate/template.json
packages/cli/templates/jquery/js/projects/empty/files/package.json
packages/cli/templates/quickstart/angular/package.json
packages/cli/templates/quickstart/jquery/index.html
packages/cli/templates/quickstart/jquery/package.json
packages/cli/templates/quickstart/react/package.json
packages/cli/templates/react/es6/index.ts
packages/cli/templates/react/es6/projects/empty/files/package.json
spec/acceptance/generate-spec.ts
spec/unit/packageManager-spec.ts

update Ignite UI for jQuery to 20.1

---

packages/igx-templates/igx-ts/bullet-graph/default/index.ts
packages/igx-templates/igx-ts/category-chart/default/index.ts
packages/igx-templates/igx-ts/custom-templates/awesome-grid/index.ts
packages/igx-templates/igx-ts/custom-templates/crm-grid/index.ts
packages/igx-templates/igx-ts/custom-templates/fintech-grid/index.ts
packages/igx-templates/igx-ts/financial-chart/default/index.ts
packages/igx-templates/igx-ts/linear-gauge/default/index.ts
packages/igx-templates/igx-ts/radial-gauge/default/index.ts

Closes #757  .  
Updating to:
"igniteui-angular-charts": "~9.1.2",
"igniteui-angular-core": "~9.1.2",
"igniteui-angular-gauges": "~9.1.2",

Updating the version of the DV related packages

---

packages/cli/templates/react/igr-es6/bullet-graph/default/files/src/views/__path__/index.js
packages/cli/templates/react/igr-es6/bullet-graph/default/index.ts
packages/cli/templates/react/igr-es6/category-chart/default/files/src/views/__path__/index.js
packages/cli/templates/react/igr-es6/category-chart/default/index.ts
packages/cli/templates/react/igr-es6/doughnut-chart/default/files/src/views/__path__/index.js
packages/cli/templates/react/igr-es6/doughnut-chart/default/index.ts
packages/cli/templates/react/igr-es6/financial-chart/default/files/src/views/__path__/index.js
packages/cli/templates/react/igr-es6/financial-chart/default/index.ts
packages/cli/templates/react/igr-es6/grid/basic/files/src/views/__path__/index.js
packages/cli/templates/react/igr-es6/grid/basic/index.ts
packages/cli/templates/react/igr-es6/grid/index.ts
packages/cli/templates/react/igr-es6/linear-gauge/default/files/src/views/__path__/index.js
packages/cli/templates/react/igr-es6/linear-gauge/default/index.ts
packages/cli/templates/react/igr-es6/pie-chart/default/files/src/views/__path__/index.js
packages/cli/templates/react/igr-es6/pie-chart/default/index.ts
packages/cli/templates/react/igr-es6/projects/_base/files/package.json
packages/cli/templates/react/igr-es6/radial-gauge/default/files/src/views/__path__/index.js
packages/cli/templates/react/igr-es6/radial-gauge/default/index.ts

Updating React LiveGrid to DataGrid

---

packages/igx-templates/IgniteUIForAngularTemplate.ts
packages/igx-templates/igx-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.component.scss
packages/igx-templates/igx-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.component.spec.ts
packages/igx-templates/igx-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.component.ts
packages/igx-templates/igx-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.module.ts
packages/igx-templates/igx-ts/dock-manager/default/index.ts
packages/igx-templates/igx-ts/dock-manager/index.ts

feat: Adding a Dock Manager template for Angular

---

.vscode/launch.json
packages/cli/lib/cli.ts
packages/core/prompt/BasePromptSession.ts
packages/core/util/App.ts

chore(step-by-step): add test flag to show option to add all templates

---

packages/igx-templates/package-resolve.spec.ts

Update the spec suite heading and group tests in two separate `describe`s

test(package-resolve): add tests for `getUpgradeablePackages`

---

packages/igx-templates/igx-ts/map/default/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/map/default/files/src/app/__path__/__filePrefix__.component.scss
packages/igx-templates/igx-ts/map/default/files/src/app/__path__/__filePrefix__.component.spec.ts
packages/igx-templates/igx-ts/map/default/files/src/app/__path__/__filePrefix__.component.ts
packages/igx-templates/igx-ts/map/default/index.ts
packages/igx-templates/igx-ts/map/index.ts

feat: Adding a Map template for Angular

---

packages/core/config/defaults.json

feat: remove angular as default choice for step by step #579

---

packages/core/templates/BaseProjectLibrary.ts
packages/igx-templates/igx-ts/groups.json
spec/unit/BaseProjectLibrary-spec.ts

fix: category reorder

---

packages/igx-templates/igx-ts/projects/_base/files/package.json
packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json

Update jszip to 350

---

packages/igx-templates/igx-ts/projects/_base/files/package.json
packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json

Updating the igniteui-angular version

Updating igniteui-angular version to 10.1.0-beta.0

---

packages/igx-templates/igx-ts/projects/_base/files/package.json
packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json

Updating igniteui-angular version to "~10.1.0"

---

CHANGELOG.md
packages/cli/package.json
packages/core/package.json
packages/core/typescript/TypeScriptFileUpdate.ts
packages/igx-templates/igx-ts/projects/_base/files/package.json
packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json
packages/igx-templates/package.json
packages/ng-schematics/package.json
spec/unit/ts-transform/TypeScriptFileUpdate-spec.ts
yarn.lock

merge vNext to master

---

packages/igx-templates/igx-ts/bullet-graph/default/index.ts
packages/igx-templates/igx-ts/category-chart/default/index.ts
packages/igx-templates/igx-ts/custom-templates/awesome-grid/index.ts
packages/igx-templates/igx-ts/custom-templates/crm-grid/index.ts
packages/igx-templates/igx-ts/custom-templates/fintech-grid/index.ts
packages/igx-templates/igx-ts/financial-chart/default/index.ts
packages/igx-templates/igx-ts/linear-gauge/default/index.ts
packages/igx-templates/igx-ts/radial-gauge/default/index.ts

chore(dv-components): Update to 10.1.3. #768

---

packages/igx-templates/igx-ts/projects/_base/files/src/app/error-routing/error-routing.module.ts

Fix app generated with cli will not load because of an error

---

packages/cli/package.json
packages/cli/templates/react/igr-es6/grid/basic/files/src/views/__path__/index.js
packages/cli/templates/react/igr-es6/grid/basic/index.ts

fix(react-grid): Add missing module #791

---

packages/igx-templates/igx-ts/projects/_base/files/package.json
packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json

chore: update to igniteui-angular@11.0.0

---

packages/igx-templates/igx-ts/grid/grid-custom/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/grid/grid-custom/index.ts

refactor(igx,custom-grid): udpate toolbar to new declarative setup

---

packages/igx-templates/igx-ts/grid/grid-custom/index.ts

fix(igx,custom-grid): assign allowFiltering when selected as option

---

packages/igx-templates/igx-ts/hierarchical-grid/hierarchical-grid-custom/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/hierarchical-grid/hierarchical-grid-custom/index.ts
packages/igx-templates/igx-ts/tree-grid/tree-grid-custom/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/tree-grid/tree-grid-custom/index.ts

Update treegrid & hierarchical grid custom template to declarative toolbar

---

CHANGELOG.md
packages/cli/package.json
packages/core/package.json
packages/igx-templates/package.json
packages/ng-schematics/package.json

release: 7.0.2

---

packages/igx-templates/igx-ts/tree/default/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/tree/default/files/src/app/__path__/__filePrefix__.component.scss
packages/igx-templates/igx-ts/tree/default/files/src/app/__path__/__filePrefix__.component.spec.ts
packages/igx-templates/igx-ts/tree/default/files/src/app/__path__/__filePrefix__.component.ts
packages/igx-templates/igx-ts/tree/default/files/src/app/__path__/local-data.ts
packages/igx-templates/igx-ts/tree/default/files/src/app/__path__/services/data.service.ts
packages/igx-templates/igx-ts/tree/default/index.ts
packages/igx-templates/igx-ts/tree/index.ts

Add template for IgxTree component.
cli should use `igniteui-angular`@~12 for this to work, as component is added in that version.

feat(igx-templates): add igx-tree template

---

packages/igx-templates/igx-ts/custom-templates/crm-grid/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/custom-templates/fintech-grid/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/custom-templates/weather-forecast/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/hierarchical-grid/hierarchical-grid-custom/index.ts
packages/igx-templates/igx-ts/input-group/default/files/src/app/__path__/__filePrefix__.component.html

Fix samples with font awesome icons 

---

packages/igx-templates/igx-ts/chip/default/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/custom-templates/fintech-grid/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/custom-templates/fintech-tree-grid/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/grid/default/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/input-group/default/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/input-group/default/files/src/app/__path__/__filePrefix__.component.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/app.component.html
packages/igx-templates/igx-ts/projects/side-nav/files/src/app/app.component.html

Fix "on" events to match the updated product event names.

Update on events across all samples

---

packages/igx-templates/igx-ts/projects/_base/files/src/app/error-routing/error/global-error-handler.service.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/login-bar/login-bar.component.html
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/login/login.component.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/models/user.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/profile/profile.component.html
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/providers/auth-provider.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/providers/base-oidc-provider.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/providers/facebook-provider.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/providers/google-provider.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/providers/microsoft-provider.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/redirect/redirect.component.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/register/register.component.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/authentication.service.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/external-auth.service.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/fake-backend.service.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/jwt-util.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/jwt.spec.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/local-storage.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/services.spec.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/user.service.ts
packages/igx-templates/igx-ts/projects/side-nav/files/src/app/app.component.ts

Angular project strict errors

---

packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
packages/igx-templates/igx-ts/custom-templates/fintech-grid/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/custom-templates/fintech-grid/files/src/app/__path__/__filePrefix__.component.ts

Added `detectChanges` in `ngAfterViewInit` to fix `ExpressionChangedAfterItHasBeenCheckedError`.
Update markup to fix `rowData` warning.
All other warnings are coming from the product and should be fixed there with next release.

fix(fintech-grid): fix console warnings and errors

---

packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.scss
packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.ts
packages/igx-templates/igx-ts/custom-templates/crm-grid/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/grid/default/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/grid/grid-custom/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/grid/grid-custom/index.ts
packages/igx-templates/igx-ts/grid/grid-summaries/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/grid/multi-column-headers/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/grid/multi-column-headers/index.ts
packages/igx-templates/igx-ts/hierarchical-grid/hierarchical-grid-custom/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/hierarchical-grid/hierarchical-grid-custom/index.ts
packages/igx-templates/igx-ts/projects/_base/index.ts
packages/igx-templates/igx-ts/tree-grid/tree-grid-custom/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/tree-grid/tree-grid-custom/index.ts
spec/unit/PromptSession-spec.ts

Update custom grids paging for 12.1

---

packages/igx-templates/igx-ts/projects/_base/files/package.json
packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json

chore(igx-ts): update igniteui-angular version to 12.1.0

---

CHANGELOG.md
packages/cli/package.json
packages/core/package.json
packages/igx-templates/package.json
packages/ng-schematics/package.json

release: 8.1.0

---

packages/igx-templates/igx-ts/bullet-graph/default/index.ts
packages/igx-templates/igx-ts/category-chart/default/index.ts
packages/igx-templates/igx-ts/custom-templates/awesome-grid/index.ts
packages/igx-templates/igx-ts/custom-templates/crm-grid/index.ts
packages/igx-templates/igx-ts/custom-templates/fintech-grid/index.ts
packages/igx-templates/igx-ts/financial-chart/default/index.ts
packages/igx-templates/igx-ts/linear-gauge/default/index.ts
packages/igx-templates/igx-ts/map/default/index.ts
packages/igx-templates/igx-ts/projects/_base/files/package.json
packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json
packages/igx-templates/igx-ts/radial-gauge/default/index.ts

Update dv component packages

---

packages/core/typescript/TypeScriptFileUpdate.ts
spec/unit/ts-transform/TypeScriptFileUpdate-spec.ts

fix(ts-transform): respect quote type from editorconfig

---

packages/igx-templates/igx-ts/projects/_base/files/package.json
packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json

chore: update with 12.2.0

---

CHANGELOG.md
packages/cli/package.json
packages/core/package.json
packages/igx-templates/package.json
packages/ng-schematics/package.json

release: 8.2.0

---

packages/cli/templates/webcomponents/igc-ts/badge/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/badge/default/index.ts
packages/cli/templates/webcomponents/igc-ts/badge/index.ts

Badge web component project with template

---

packages/cli/templates/webcomponents/igc-ts/checkbox/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/checkbox/default/index.ts
packages/cli/templates/webcomponents/igc-ts/checkbox/index.ts

Checkbox web component project with template

---

packages/cli/templates/webcomponents/igc-ts/form/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/form/default/index.ts
packages/cli/templates/webcomponents/igc-ts/form/index.ts

Form web component project with template

---

packages/cli/templates/webcomponents/igc-ts/icon-button/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/icon-button/default/index.ts
packages/cli/templates/webcomponents/igc-ts/icon-button/index.ts

Icon button web component project with template

---

packages/cli/templates/webcomponents/igc-ts/icon/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/icon/default/index.ts
packages/cli/templates/webcomponents/igc-ts/icon/index.ts

Icon web component project with template

---

packages/cli/templates/webcomponents/igc-ts/input/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/input/default/index.ts
packages/cli/templates/webcomponents/igc-ts/input/index.ts

Input web component project with template

---

packages/cli/templates/webcomponents/igc-ts/link-button/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/link-button/default/index.ts
packages/cli/templates/webcomponents/igc-ts/link-button/index.ts

Link button web component project with template

---

packages/cli/templates/webcomponents/igc-ts/navbar/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/navbar/default/index.ts
packages/cli/templates/webcomponents/igc-ts/navbar/index.ts

Navbar web component project with template

---

packages/cli/templates/webcomponents/igc-ts/radio-group/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/radio-group/default/index.ts
packages/cli/templates/webcomponents/igc-ts/radio-group/index.ts

Radio group web component project with template

---

packages/cli/templates/webcomponents/igc-ts/radio/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/radio/default/index.ts
packages/cli/templates/webcomponents/igc-ts/radio/index.ts

Radio web component project with template

---

packages/cli/templates/webcomponents/igc-ts/icon-button/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/icon-button/default/index.ts
packages/cli/templates/webcomponents/igc-ts/icon/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/projects/empty/files/package.json

Fixing issues in Icon and Icon Button views

Improving icon and icon-button views

---

packages/cli/templates/webcomponents/igc-ts/projects/empty/files/src/app.ts

- Adding igc-ripple to navDrawer items
- Clicking the NavDrawer item, not just the <a>, is changing the view

Adding igc-ripple to navdrawer items

---

packages/cli/templates/webcomponents/igc-ts/projects/empty/files/index.html

Changing the default theme for webcomponents project to "bootstrap" instead of "material"

Updating default theme to be bootstrap

---

packages/cli/templates/webcomponents/igc-ts/icon-button/default/index.ts
packages/cli/templates/webcomponents/igc-ts/icon/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/navbar/default/index.ts

・fixing the ids for Navbar and Icon button
・changing arguments of define()

Fixing ids for Navbar and Icon Button

---

packages/igx-templates/igx-ts/bullet-graph/default/index.ts
packages/igx-templates/igx-ts/category-chart/default/index.ts
packages/igx-templates/igx-ts/custom-templates/awesome-grid/index.ts
packages/igx-templates/igx-ts/custom-templates/crm-grid/index.ts
packages/igx-templates/igx-ts/custom-templates/fintech-grid/index.ts
packages/igx-templates/igx-ts/financial-chart/default/index.ts
packages/igx-templates/igx-ts/linear-gauge/default/index.ts
packages/igx-templates/igx-ts/map/default/index.ts
packages/igx-templates/igx-ts/radial-gauge/default/index.ts

chore(angukar): update DV packages to 13.0.0

---

packages/cli/templates/webcomponents/igc-ts/groups.json
packages/cli/templates/webcomponents/igc-ts/pie-chart/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/pie-chart/default/files/src/app/__path__/sampleData.ts
packages/cli/templates/webcomponents/igc-ts/pie-chart/default/index.ts
packages/cli/templates/webcomponents/igc-ts/pie-chart/index.ts
packages/cli/templates/webcomponents/igc-ts/projects/empty/files/package.json
packages/core/templates/BaseTemplateManager.ts

Adding a Pie Chart webcomponents view. Example was taken from this topic: https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/charts/types/pie-chart

Adding Pie Chart view

---

package.json
packages/cli/package.json
packages/core/package.json
packages/igx-templates/package.json
packages/ng-schematics/package.json
yarn.lock

chore(*): properly limit typescript deps in packages

---

packages/igx-templates/Update.spec.ts
packages/igx-templates/Update.ts

fix(angular): new theme imports upgrade packages

---

packages/cli/templates/webcomponents/igc-ts/grid/default/index.ts
packages/cli/templates/webcomponents/igc-ts/grid/index.ts
packages/cli/templates/webcomponents/igc-ts/groups.json
packages/cli/templates/webcomponents/igc-ts/list/default/index.ts
packages/cli/templates/webcomponents/igc-ts/list/index.ts

Temporary hide the igcDataGrid view from the Step-by-Step wizard menu.

Hide igcDataGrid view

---

packages/igx-templates/igx-ts/projects/_base/files/package.json
packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json

chore: update official 13.0.0

---

.github/ISSUE_TEMPLATE.md

Web components were missing from the available framework options in the issue template

Add Web Components framework to the issue template

---

packages/igx-templates/igx-ts/projects/empty/files/src/app/home/home.component.scss

fix(schematics): fix home import without placeholder

---

packages/cli/templates/webcomponents/igc-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.ts

Fix Dock Manager lint errors

---

packages/cli/templates/webcomponents/igc-ts/projects/empty/files/src/app.ts

Closes #968  .  
Removing redundant comma marks.

Fixing web-components navigation issues

---

packages/cli/templates/webcomponents/igc-ts/slider/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/slider/default/index.ts
packages/cli/templates/webcomponents/igc-ts/slider/index.ts

Adding the slider web component.

Adding Slider web component

---

packages/cli/templates/webcomponents/igc-ts/avatar/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/badge/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/button/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/calendar/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/card/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/checkbox/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/custom-templates/subscription-form/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/financial-chart/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/form/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/grid/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/grid/grid-editing/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/grid/grid-summaries/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/icon-button/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/icon/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/input/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/linear-gauge/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/list/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/navbar/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/pie-chart/default/files/src/app/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/pie-chart/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/radial-gauge/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/radio-group/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/ripple/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/slider/default/files/src/app/__path__/__filePrefix__.component.test.ts
packages/cli/templates/webcomponents/igc-ts/switch/default/files/src/app/__path__/__filePrefix__.component.test.ts

Adding tests for the web components

---

packages/cli/templates/webcomponents/TypeScriptFileUpdate.ts
packages/cli/templates/webcomponents/igc-ts/projects/empty/files/__dot__editorconfig

Set correct quote_type to web components project

---

packages/ng-schematics/src/cli-config/index_spec.ts
packages/ng-schematics/src/utils/theme-import.ts

Closes https://github.com/IgniteUI/igniteui-cli/issues/1022

Use @use rule to add default theming module

---

packages/cli/templates/quickstart/angular/package.json
packages/igx-templates/igx-ts/projects/_base/files/package.json
packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json

Updating to 
"igniteui-angular": "~13.2.0",
"igniteui-angular-wrappers": "~13.1.0"

Update to igniteui-angular 13.2.0

---

packages/core/packages/PackageManager.ts
spec/unit/packageManager-spec.ts

Closes https://github.com/IgniteUI/igniteui-cli/issues/1035

Skip setting up child install tasks for new projects

---

packages/core/packages/PackageManager.ts
packages/igx-templates/igx-ts/bullet-graph/default/index.ts
packages/igx-templates/igx-ts/category-chart/default/index.ts
packages/igx-templates/igx-ts/custom-templates/awesome-grid/index.ts
packages/igx-templates/igx-ts/custom-templates/crm-grid/index.ts
packages/igx-templates/igx-ts/custom-templates/fintech-grid/index.ts
packages/igx-templates/igx-ts/dock-manager/default/index.ts
packages/igx-templates/igx-ts/financial-chart/default/index.ts
packages/igx-templates/igx-ts/linear-gauge/default/index.ts
packages/igx-templates/igx-ts/map/default/index.ts
packages/igx-templates/igx-ts/radial-gauge/default/index.ts
spec/unit/packageManager-spec.ts

- Updating charts, gauges, maps packages to v. 14
- Updating custom templates dependencies
- Removing --legacy-peer-deps flags

Updating maps to version 14

---

packages/cli/templates/webcomponents/igc-ts/dropdown/default/files/src/app/__path__/__filePrefix__.test.ts
packages/cli/templates/webcomponents/igc-ts/dropdown/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/dropdown/default/index.ts
packages/cli/templates/webcomponents/igc-ts/dropdown/index.ts
packages/cli/templates/webcomponents/igc-ts/expansion-panel/default/files/src/app/__path__/__filePrefix__.test.ts
packages/cli/templates/webcomponents/igc-ts/expansion-panel/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/expansion-panel/default/index.ts
packages/cli/templates/webcomponents/igc-ts/expansion-panel/index.ts
packages/cli/templates/webcomponents/igc-ts/tree/default/files/src/app/__path__/__filePrefix__.test.ts
packages/cli/templates/webcomponents/igc-ts/tree/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/tree/default/index.ts
packages/cli/templates/webcomponents/igc-ts/tree/index.ts

Add missing Web Components templates

---

packages/cli/templates/webcomponents/igc-ts/card/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/custom-templates/subscription-form/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/dropdown/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/expansion-panel/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/form/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/list/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/navbar/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/projects/_base/files/package.json
packages/cli/templates/webcomponents/igc-ts/projects/side-nav/files/src/app/app.ts
packages/cli/templates/webcomponents/igc-ts/radio-group/default/files/src/app/__path__/__filePrefix__.ts
packages/cli/templates/webcomponents/igc-ts/tree/default/files/src/app/__path__/__filePrefix__.ts

chore(wc): simlify defineComponents() after 3.3.0

---

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/src/app/app.ts
packages/cli/templates/webcomponents/igc-ts/projects/_base/files/styles.css

Closes # .  
Fix background and color CSS properties for body in webcomponents base application.
Fix also app-root styling and markup.

Fix global styles

---

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/styles.css

Closes # .  
Fix background fallback color.

Fix background fallback color

---

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/src/app/app.ts

router-outlet {
width: 100%;
}

Adding width: 100% to router-outlet elements

---

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/styles.css

Reverting body height

---

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/__dot__github/workflows/node.js.yml

Adding  a yml file for GitHub actions for Web Components projects.

GitHub actions for Web Components

---

packages/cli/templates/webcomponents/TypeScriptFileUpdate.ts

Add a flag to generate only single quoted strings when generating paths.

Generate single quotes in paths

---

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/rollup.config.mjs

Changing the babel function call

---

packages/igx-templates/igx-ts/projects/_base/files/angular.json
packages/igx-templates/igx-ts/projects/_base/files/tsconfig.json
packages/igx-templates/igx-ts/projects/_base/index.ts
packages/ng-schematics/src/utils/theme-import.ts
spec/unit/PromptSession-spec.ts

Adding the $surface argument

---

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/rollup.config.mjs

Suppress rollup and babel warnings

---

packages/igx-templates/igx-ts/pivot-grid/default/files/src/app/__path__/__filePrefix__.component.spec.ts

Adding NoopAnimationsModule and removing FormsModule.

---

packages/igx-templates/igx-ts/hierarchical-grid/hierarchical-grid-batch-editing/files/src/app/__path__/__filePrefix__.component.html

Removing "on" prefix from event names.

---

CHANGELOG.md
packages/cli/package.json
packages/cli/templates/webcomponents/igc-ts/projects/_base/files/__dot__gitignore
packages/cli/templates/webcomponents/igc-ts/projects/_base/files/package.json
packages/cli/templates/webcomponents/igc-ts/projects/_base/files/rollup.config.mjs
packages/cli/templates/webcomponents/igc-ts/projects/_base/files/tsconfig.json
packages/cli/templates/webcomponents/igc-ts/projects/_base/files/tsconfig.test.json
packages/cli/templates/webcomponents/igc-ts/projects/_base/files/web-test-runner.config.mjs
packages/cli/templates/webcomponents/igc-ts/projects/_base_with_home/files/package.json
packages/core/package.json
packages/igx-templates/igx-ts/projects/_base/files/angular.json
packages/igx-templates/igx-ts/projects/_base/files/tsconfig.json
packages/igx-templates/igx-ts/projects/_base/index.ts
packages/igx-templates/package.json
packages/ng-schematics/package.json
packages/ng-schematics/src/utils/theme-import.ts
spec/unit/PromptSession-spec.ts

merge 11.0.x into 11.1.x

---

packages/igx-templates/igx-ts/projects/_base/files/package.json
packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json

chore(igx-ts): remove igniteui-theming package

---

packages/igx-templates/igx-ts-legacy/projects/_base/files/package.json
packages/igx-templates/igx-ts-legacy/projects/side-nav-auth/files/package.json
packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json

fix(igx): remove prod config for ng build

---

packages/igx-templates/igx-ts-legacy/projects/_base/files/src/app/app-routing.module.ts
packages/igx-templates/igx-ts-legacy/projects/_base_with_home/files/src/app/app-routing.module.ts
packages/igx-templates/igx-ts-legacy/projects/empty/files/src/app/app-routing.module.ts
packages/igx-templates/igx-ts/projects/_base/files/src/app/app.config.ts
packages/igx-templates/igx-ts/projects/_base_with_home/files/src/app/app.config.ts
packages/igx-templates/igx-ts/projects/empty/files/src/app/app.config.ts
packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/app.config.ts
packages/igx-templates/igx-ts/projects/side-nav/files/src/app/app.config.ts

Enables binding information from the Router state directly to the inputs of the component in Route configurations.

Enable binding information from the Router state to the components' inputs

---

packages/cli/templates/react/igr-ts/projects/_base/files/__dot__github/workflows/node.js.yml
packages/cli/templates/react/igr-ts/projects/_base/index.ts

fix(igr-ts): add github workflows folder

---

packages/core/typescript/TypeScriptFileUpdate.ts
packages/core/typescript/TypeScriptUtils.ts
packages/ng-schematics/src/cli-config/index.ts
packages/ng-schematics/src/cli-config/index_spec.ts

feat(ng-add): add setup config provideAnimations

---

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/package.json

Closes 29319 from Indigo_Platform

fix(WebComponents): Removing an unnecessary ` from package.json

---

packages/igx-templates/igx-ts/projects/_base/files/angular.json

The size of all components + all scenarios demo is:

chore(ng): update budget

---

packages/igx-templates/igx-ts-legacy/projects/_base/files/src/app/app-routing.module.ts

Updating igx-ts-legacy base template

---

packages/cli/templates/react/igr-ts/projects/_base/files/__dot__editorconfig
packages/cli/templates/react/igr-ts/projects/_base/files/ignite-ui-cli.json
packages/cli/templates/react/igr-ts/projects/_base/files/package.json
packages/cli/templates/react/igr-ts/projects/_base/files/src/app/app.test.tsx
packages/cli/templates/react/igr-ts/projects/_base/files/src/app/app.tsx
packages/cli/templates/react/igr-ts/projects/_base/files/src/app/style-utils.ts
packages/cli/templates/react/igr-ts/projects/_base/files/src/main.tsx
packages/cli/templates/react/igr-ts/projects/_base/files/src/vite-env.d.ts
packages/cli/templates/react/igr-ts/projects/_base/files/tsconfig.json
packages/cli/templates/react/igr-ts/projects/_base/files/vite.config.ts

Closes #1217  
Added `vite-env.d.ts` file in `src` folder. This file adds module declarations needed for TypeScript.
Also added `.editorconfig` file for maintaining consistent coding styles.
Finally fix all the indentations in all files across react base template.

Update react base template

---

packages/cli/templates/react/igr-ts/projects/_base/files/package.json
packages/cli/templates/react/igr-ts/projects/_base/files/src/app/app.test.tsx

Related to [React tests are not passing](https://infragistics.visualstudio.com/Indigo_Platform/_sprints/taskboard/Indigo_Platform%20Team/Indigo_Platform/2024/Q1/22-Mar-24%20Sprint%206?workitem=30226)

fix: add elements internal polyfill to base template

---

packages/cli/templates/react/igr-ts/projects/_base/files/src/app/style-utils.ts

fix(Lint): Fixed styles typing in style-utils

---

packages/cli/package.json
packages/core/package.json
packages/core/typescript/TypeScriptFileUpdate.ts
packages/igx-templates/package.json
packages/ng-schematics/package.json

Closes [#30324](https://infragistics.visualstudio.com/Indigo_Platform/_workitems/edit/30324)
Generate default redirect routes for module based & standalone projects.

Generate default redirect routes for NG

---

packages/cli/templates/react/igr-ts/projects/_base/files/__dot__eslintrc.cjs

feat(react): turn off no-explicit-any in eslint

---

packages/cli/templates/react/igr-ts/projects/_base/files/src/app/app.tsx

Remove obsolete classes in app.tsx

---

packages/cli/templates/react/igr-ts/projects/_base/files/src/main.tsx

Closes [https://infragistics.visualstudio.com/Indigo_Platform/_workitems/edit/30893](https://infragistics.visualstudio.com/Indigo_Platform/_workitems/edit/30893) .

fix(react): fix null type build error in main.tsx

---

packages/igx-templates/igx-ts/projects/_base/files/angular.json

Add stylePreprocessorOptions in order to fix tests for generated projects

chore(ng standalone): add stylePreprocessorOptions for test

---

packages/cli/package.json
packages/core/package.json
packages/igx-templates/igx-ts-legacy/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts-legacy/custom-templates/crm-grid/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts-legacy/list/default/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts-legacy/projects/_base/files/package.json
packages/igx-templates/igx-ts-legacy/projects/side-nav-auth/files/package.json
packages/igx-templates/igx-ts-legacy/tooltip/default/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/custom-templates/crm-grid/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/list/default/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/igx-ts/projects/_base/files/package.json
packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json
packages/igx-templates/igx-ts/tooltip/default/files/src/app/__path__/__filePrefix__.component.html
packages/igx-templates/package.json
packages/ng-schematics/package.json

https://github.com/IgniteUI/igniteui-angular/releases/tag/17.2.0-beta.2
* feat(calendar): implement improved design and functionality by @desig9stein in https://github.com/IgniteUI/igniteui-angular/pull/13650
* feat(themes): updated Indigo component themes by @simeonoff in https://github.com/IgniteUI/igniteui-angular/pull/14064
* feat(advance-filtering): Emit filtering event when use advanced filtering by @georgianastasov in https://github.com/IgniteUI/igniteui-angular/pull/14078
* fix(date-picker): update toggle icon by @SisIvanova in https://github.com/IgniteUI/igniteui-angular/pull/14137
* fix(date-time-editor): handle iso date string for mask value by @dobromirts in https://github.com/IgniteUI/igniteui-angular/pull/14032
* fix(esf): reset forOf startIndex on esf columnChange by …

chore: update with igniteui-angular@17.2.0-beta.2

---

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/package.json
packages/cli/templates/webcomponents/igc-ts/projects/_base_with_home/files/package.json

Valadzhov/bump web dev server in webc templates 13.3.x

---

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/package.json
packages/cli/templates/webcomponents/igc-ts/projects/_base_with_home/files/package.json

Fixes https://infragistics.visualstudio.com/Indigo_Platform/_workitems/edit/32768/

chore(webc): Add @types/mocha to the WebComponents templates - master

---

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/package.json
packages/cli/templates/webcomponents/igc-ts/projects/_base_with_home/files/package.json

Fixes https://infragistics.visualstudio.com/Indigo_Platform/_workitems/edit/32768/

chore(webc): Add @types/mocha to the WebComponents templates - 13.2.x

---

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/package.json
packages/cli/templates/webcomponents/igc-ts/projects/_base_with_home/files/package.json

Fixes https://infragistics.visualstudio.com/Indigo_Platform/_workitems/edit/32768/

chore(webc): Add @types/mocha to the WebComponents templates - 13.3.x

---

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/package.json
packages/cli/templates/webcomponents/igc-ts/projects/_base_with_home/files/package.json

Fixes https://infragistics.visualstudio.com/Indigo_Platform/_workitems/edit/32768/

chore(webc): Add @types/mocha to the WebComponents templates - 13.4.x

---

packages/cli/templates/react/igr-ts/projects/_base/files/src/app/app-routes.tsx

Closes [32836](https://infragistics.visualstudio.com/Indigo_Platform/_sprints/taskboard/Indigo_Platform%20Team/Indigo_Platform/2024/Q3/19-Jul-24%20Sprint%2014?workitem=32836) in CodeGen .

fix(igr-ts): add new lines in base app routes file

---

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/__dot__eslintrc.json

Turn off no-explicit-any rule for wc

---

packages/cli/templates/react/igr-ts/projects/top-nav/files/src/app/app.test.tsx

This test file properly passes tests now
Closes #1266  .  

Added overriding app.test.tsx for default top navigation template

---

packages/cli/templates/react/igr-ts/projects/_base/files/__dot__github/workflows/github.io.yml
packages/cli/templates/webcomponents/igc-ts/projects/_base/files/__dot__github/workflows/github.io.yml

Closes # .  
Fix branches in github pages templates for react and web components

Add fixes in react and wc templates

---

.github/workflows/nodejs.yml

build(coverage): bumping coveralls action version

---

packages/cli/templates/react/igr-ts/projects/_base/files/__dot__github/workflows/github.io.yml
packages/cli/templates/react/igr-ts/projects/_base/files/__dot__github/workflows/node.js.yml
packages/cli/templates/webcomponents/igc-ts/projects/_base/files/__dot__github/workflows/github.io.yml
packages/cli/templates/webcomponents/igc-ts/projects/_base/files/__dot__github/workflows/node.js.yml
packages/igx-templates/igx-ts-legacy/projects/_base/files/__dot__github/workflows/github.io.yml
packages/igx-templates/igx-ts-legacy/projects/_base/files/__dot__github/workflows/node.js.yml
packages/igx-templates/igx-ts-legacy/projects/_base_with_home/files/__dot__github/workflows/github.io.yml
packages/igx-templates/igx-ts-legacy/projects/_base_with_home/files/__dot__github/workflows/node.js.yml
packages/igx-templates/igx-ts/projects/_base/files/__dot__github/workflows/github.io.yml
packages/igx-templates/igx-ts/projects/_base/files/__dot__github/workflows/node.js.yml
packages/igx-templates/igx-ts/projects/_base_with_home/files/__dot__github/workflows/github.io.yml
packages/igx-templates/igx-ts/projects/_base_with_home/files/__dot__github/workflows/node.js.yml

replace node versions 18 and 20 with 22 in all templates and fix build logic for angular templates

update node version in yml files and fix build logic for angular templates

---

CHANGELOG.md
packages/cli/package.json
packages/core/package.json
packages/igx-templates/constants.ts
packages/igx-templates/igx-ts-legacy/projects/_base/files/package.json
packages/igx-templates/igx-ts-legacy/projects/side-nav-auth/files/package.json
packages/igx-templates/igx-ts/projects/_base/files/package.json
packages/igx-templates/package.json
packages/ng-schematics/package.json

🎉 This update includes:
- `igniteui-angular` version [19.0.0](https://github.com/IgniteUI/igniteui-angular/releases/tag/19.0.0).
* Allow reordering of array literal expressions by @jackofdiamond5 in https://github.com/IgniteUI/igniteui-cli/pull/1323
* Add pages deployment variable logic and fixes in github pages yaml files by @Hristo313 in https://github.com/IgniteUI/igniteui-cli/pull/1337
* chore(templates): Updating the versions for Angular 19 by @valadzhov in https://github.com/IgniteUI/igniteui-cli/pull/1340
* chore(tsconfig-pack): Add skipLibCheck by @valadzhov in https://github.com/IgniteUI/igniteui-cli/pull/1344
**Full Changelog**: https://github.com/IgniteUI/igniteui-cli/compare/v14.2.3...v14.3.0

chore: release 14.3.0

---

packages/cli/package.json
packages/core/package.json
packages/igx-templates/package.json
packages/ng-schematics/package.json

chore: release 14.3.1

---

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/__dot__github/workflows/github-pages.yml

fix navigation and unexpected '>' symbol in web components github pages workflow

Add step in web components github pages workflow to fix navigation

---

CHANGELOG.md
packages/cli/package.json
packages/core/package.json
packages/igx-templates/package.json
packages/ng-schematics/package.json

chore: release version 14.3.4

---

CHANGELOG.md
packages/cli/package.json
packages/core/package.json
packages/igx-templates/package.json
packages/ng-schematics/package.json

chore: release version 14.3.5

---

packages/cli/migrations/migration-collection.json
packages/ng-schematics/src/migrations/migration-collection.json

https://github.com/IgniteUI/igniteui-angular/pull/13712

fix(migrations): enable encapsulation for migrations

---

packages/cli/templates/webcomponents/igc-ts/navbar/default/files/src/app/__path__/__filePrefix__.ts

move register icon to igniteui-web-components import

Fix wc navbar register icon import

---

CHANGELOG.md
packages/cli/package.json
packages/core/package.json
packages/igx-templates/package.json
packages/ng-schematics/package.json

release version 14.3.8

---

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/vite.config.ts

feat: enable silent mode in Vite configuration for improved build output

---

packages/cli/package.json
packages/cli/templates/react/igr-ts/projects/_base/files/__dot__github/workflows/github-pages.yml
packages/core/package.json
packages/igx-templates/igx-ts-legacy/projects/_base/files/__dot__github/workflows/github-pages.yml
packages/igx-templates/igx-ts-legacy/projects/_base_with_home/files/__dot__github/workflows/github-pages.yml
packages/igx-templates/igx-ts/projects/_base/files/__dot__github/workflows/github-pages.yml
packages/igx-templates/igx-ts/projects/_base_with_home/files/__dot__github/workflows/github-pages.yml
packages/igx-templates/package.json
packages/ng-schematics/package.json

Add step for fixing static data paths for react and assets for angular.

fix: static data paths when deploy to github pages

---

packages/cli/package.json
packages/cli/templates/webcomponents/igc-ts/projects/_base/files/__dot__github/workflows/github-pages.yml
packages/core/package.json
packages/igx-templates/package.json
packages/ng-schematics/package.json

Add fixes for web components Github pages workflow needed after changing the configuration from rollup to vite.

fix: paths in web components github pages workflow

---

CHANGELOG.md
packages/cli/package.json
packages/core/package.json
packages/igx-templates/package.json
packages/ng-schematics/package.json

chore: release version 14.3.13

---

CHANGELOG.md
packages/cli/package.json
packages/core/package.json
packages/igx-templates/package.json
packages/ng-schematics/package.json

* chore(igx-templates): bump to ng 19.2.0 by @valadzhov in https://github.com/IgniteUI/igniteui-cli/pull/1392
**Full Changelog**: https://github.com/IgniteUI/igniteui-cli/compare/v14.3.18...v14.4.0

chore: Release 14.4.0

---

CHANGELOG.md
packages/cli/package.json
packages/core/package.json
packages/igx-templates/package.json
packages/ng-schematics/package.json

chore: release version 14.4.4

---

packages/cli/templates/react/igr-ts/doughnut-chart/default/files/src/app/__path__/__filePrefix__.tsx
packages/cli/templates/react/igr-ts/grid/basic/files/src/app/__path__/__filePrefix__.tsx
packages/cli/templates/react/igr-ts/pie-chart/default/files/src/app/__path__/__filePrefix__.tsx

Fix missing argument for useRef in chart compoinents and fix type names in grid component.

fix(react): add missing argument and fix incorrect types

---

packages/igx-templates/igx-ts-legacy/custom-templates/crm-grid/files/src/app/__path__/__filePrefix__.component.scss
packages/igx-templates/igx-ts/custom-templates/crm-grid/files/src/app/__path__/__filePrefix__.component.scss

Replace button with css-vars function.

fix(angular): fix theme errors

---

.vscode/launch.json
packages/cli/lib/templates/IgniteUIForReactTemplate.ts

fix: set default route
