IgniteUI/igniteui-cli

lib/packages/PackageManager.ts
=> fix(npm): add registry URL trailing slash, required for npm 5.5.1+

lib/ProjectConfig.ts, lib/PromptSession.ts, lib/Util.ts, lib/cli.ts, lib/commands/add.ts, lib/commands/config.ts, lib/commands/new.ts, lib/config/defaults.json, lib/types/Config.d.ts, spec/acceptance/config-spec.ts, spec/acceptance/help-spec.ts, spec/helpers/utils.ts, spec/unit/add-spec.ts, spec/unit/config-spec.ts, spec/unit/new-spec.ts
Initial changes for #67
The would-be page in the wiki:
---
The `ig config` performs read and write operation on the Ignite UI CLI configuration settings. The CLI stores configuration in an `ignite-ui-cli.json` file matching the [`Config`](https://github.com/IgniteUI/igniteui-cli/blob/master/lib/types/Config.d.ts) interface. Project structures created with the CLI include such file as local configuration and a per-user file can provide global defaults. The global file is stored under the current user home directory - usually `/home/<user>` for Unix and `C:\Users\<user>` for Windows. 
Config is split into [sub-commands](#sub-commands) for each operation:
```bash
ig config <get|set|add> <property> [value]
```
The following properties are available globally:
Property |    Type    | …
=> Global config and command

templates/angular/igx-ts/carousel/default/files/src/app/__path__/__name__.component.html, templates/angular/igx-ts/custom-templates/awesome-grid/index.ts, templates/angular/igx-ts/date-picker/default/files/src/app/__path__/__name__.component.html, templates/angular/igx-ts/projects/empty/files/package.json, templates/angular/igx-ts/projects/empty/files/src/app/app.component.css, templates/angular/igx-ts/projects/empty/files/src/app/app.component.html, templates/angular/igx-ts/projects/empty/files/src/app/home/home.component.css, templates/angular/igx-ts/projects/empty/files/src/app/home/home.component.html
Set responsive directives and styles for home and existing component templates.
Using igxLayout. Update the _ng serve_ to open a new browser instance when serving the app via _ng serve -o_
=> fix: set responsive directives and styles for home and existing component templates.

lib/Util.ts, lib/cli.ts, lib/commands/add.ts, lib/commands/build.ts, lib/commands/config.ts, lib/commands/generate.ts, lib/commands/new.ts, lib/commands/quickstart.ts, lib/commands/start.ts, lib/commands/test.ts, spec/acceptance/help-spec.ts, spec/acceptance/new-spec.ts, spec/unit/add-spec.ts
Closes #173
cli.ts - reordering the commands to show correctly in the help
for all commands change the description as discussed with UX
fix all failing tests
=> fix: change the regex to allow single letter name

.vscode/launch.json, lib/PromptSession.ts, lib/cli.ts, lib/commands/doc.ts, package-lock.json, package.json, spec/acceptance/help-spec.ts, spec/unit/doc-spec.ts
#66 
Add doc command, allowing users to search the infragistics help for a given term
=> feat: add doc command #66

lib/packages/PackageManager.ts, spec/unit/packageManager-spec.ts
in installPackages method enable skipAnalytic in order to not send data before npm install, and disable it after
Closes #241
=> fix: in installPackages method enable skipAnalytic

templates/angular/igx-ts/projects/empty/files/src/polyfills.ts
=> Enable required IE11 polyfills by default in Ignite UI for Angular project

templates/angular/igx-ts/projects/empty/files/package.json
chore: freeze igniteui-angular version to 6.0.0, update the cli internal reference to use minor version
=> chore: freeze igniteui-angular version to 6.0.0

lib/commands/start.ts
Undefined check for argv.port, that handles updated projects without defaultPort prop set in ignite-ui-cli.json
=> fix: Undefined check for argv.port

lib/BaseComponent.ts, lib/BaseProjectLibrary.ts, lib/MultiTemplateComponent.ts, lib/PromptSession.ts, lib/types/Component.d.ts, spec/unit/BaseProjectLibrary-spec.ts, templates/angular/igx-ts/grid/index.ts
Closes #303 .  
Also bumping the Grid in Ignite UI for Angular back on top of the group
=> Add `groupPriority` to sort components within a group

templates/angular/igx-ts/carousel/default/index.ts, templates/angular/igx-ts/list/default/index.ts, templates/angular/igx-ts/tabbar/default/index.ts
Closes #273.  
List, Carousel and Tabbar (Bottom-Nav) component templates were missing some module dependencies.
This caused the app to fail to render if these were added to a custom module (non app.module.ts).
Dependencies are now added.
=> Templates - Angular - Add module dependencies to component templates

lib/commands/test.ts
We were wrongly call .project over the Config.project type. Now we are calling directly the necessary properties of the project.
Closes #373
=> Remove calling of project over project, fix #373

templates/angular/igx-ts/projects/empty/files/package.json
=> chore(igx): limit igniteui-angular to 6.1.x for existing projects

lib/commands/quickstart.ts, lib/commands/start.ts, lib/packages/PackageManager.ts, package-lock.json, package.json, spec/jasmine-runner.ts, spec/tslint.json, spec/unit/packageManager-spec.ts, spec/unit/quickstart-spec.ts, templates/angular/igx-ts/projects/empty/files/src/app/app.component.html, templates/angular/igx-ts/projects/empty/files/src/app/app.component.scss, templates/angular/igx-ts/projects/empty/files/src/styles.scss, templates/jquery/js/projects/empty/files/package.json, templates/quickstart/angular/package.json, templates/quickstart/jquery/package.json, templates/quickstart/react/package.json
- Adjust Ignite UI for Angular project content height
- In Ignite UI for JavaScript projects when upgrading to full package, respect the installed version range
- General: Drop lite-server/browser-sync as package dependencies (moved to dev) so those are not installed with the igniteui-cli package, but rather in the projects that need them.
=> Misc fixes

templates/angular/igx-ts/grid/grid-summaries/files/src/app/__path__/__name__.component.ts
=> Fix CustomDateSummary result

templates/react/igr-es6/bullet-graph/default/index.ts, templates/react/igr-es6/category-chart/default/index.ts, templates/react/igr-es6/doughnut-chart/default/index.ts, templates/react/igr-es6/financial-chart/default/files/src/views/__path__/index.js, templates/react/igr-es6/financial-chart/default/files/src/views/__path__/style.css, templates/react/igr-es6/financial-chart/default/files/src/views/__path__/test.js, templates/react/igr-es6/financial-chart/default/index.ts, templates/react/igr-es6/financial-chart/index.ts, templates/react/igr-es6/grid/basic/index.ts, templates/react/igr-es6/linear-gauge/default/index.ts, templates/react/igr-es6/pie-chart/default/index.ts, templates/react/igr-es6/projects/_base/files/package.json, templates/react/igr-es6/radial-gauge/default/index.ts
Closes #445 .  
The financial chart template crashes on destroy, so a new public package of `igniteui-react-charts` has to be published before this is merged
=> feat(igr): add financial chart template to igr-es6 templates

lib/PromptSession.ts, spec/unit/PromptSession-spec.ts
When there is single user choice we make the choice without asking the user. In this case we should send the information to GA as if the user has made the choice. Up to now this was done for `framework` and `projectType`. With this PR `projTemplate` and `theme` are added.
Closes #461
=> Add projTemplate and theme to GA

templates/angular/igx-ts/bullet-graph/default/files/src/app/__path__/__name__.component.spec.ts, templates/angular/igx-ts/category-chart/default/files/src/app/__path__/__name__.component.spec.ts, templates/angular/igx-ts/financial-chart/default/files/src/app/__path__/__name__.component.spec.ts, templates/angular/igx-ts/linear-gauge/default/files/src/app/__path__/__name__.component.spec.ts, templates/angular/igx-ts/radial-gauge/default/files/src/app/__path__/__name__.component.spec.ts
=> Disable animation for gauge tests, drop redundant wait on charts

packages/ng-schematics/src/ng-new/index.ts
Related #595 .  
Do not try to run `start` command if `skipInstall` or `allOptionsProvided`
=> feat(schematics): skip start task if skipInstall === true

packages/igx-templates/IgniteUIForAngularTemplate.ts, packages/ng-schematics/src/component/index.ts
Closes #604.  
The App's fs was never set to virtual when calling the component schematic w/ all options.
This should *not* affect the `ng-new` and `component` w/ prompt options in no way
=> fix(schematics): set virtual FS in proper stage

templates/angular/igx-ts/autocomplete/autocomplete-custom/index.ts, templates/angular/igx-ts/autocomplete/autocomplete-extended/index.ts, templates/angular/igx-ts/hierarchical-grid/hierarchical-grid-custom/index.ts
Closes #606 
While looking at the other templates I found that the two autocomplete templates share the same id. ~I changed them as well so now they are `custom-autocomplete` and `extended-autocomplete`.~
I changed the enhanced autocomplete's id to `enhanced-autocomplete`.
=> Check if there is provided user configuration - master

lib/templates/AngularTemplate.ts, spec/unit/base-templates/AngularTemplate-spec.ts, templates/angular/igx-ts/hierarchical-grid/hierarchical-grid-custom/index.ts
Closes #618   
The `generateFiles` method in the Angular template was executing `Object.assign` with **all** values of the keys of the passed config object. If the **value** was a string, it lead to messy results (as described in the issue).
=> fix(add): only take into account 'extraConfig' in template parsing, #618

templates/quickstart/react/package.json, templates/react/es6/projects/empty/files/package.json
Closes #635 .  
The `quickstart` project doesn't really use sass, but it's nice to have consistency.
=> fix(react): update react projects to use node-sass ^4.9.0

templates/angular/igx-ts/bullet-graph/default/files/src/app/__path__/__name__.component.spec.ts, templates/angular/igx-ts/bullet-graph/default/files/src/app/__path__/__name__.component.ts, templates/angular/igx-ts/bullet-graph/default/index.ts, templates/angular/igx-ts/category-chart/default/files/src/app/__path__/__name__.component.spec.ts, templates/angular/igx-ts/category-chart/default/files/src/app/__path__/__name__.component.ts, templates/angular/igx-ts/category-chart/default/index.ts, templates/angular/igx-ts/custom-templates/fintech-grid/files/src/app/__path__/__name__.component.spec.ts, templates/angular/igx-ts/custom-templates/fintech-grid/files/src/app/__path__/__name__.component.ts, templates/angular/igx-ts/custom-templates/fintech-grid/index.ts, templates/angular/igx-ts/financial-chart/default/files/src/app/__path__/__name__.component.spec.ts, templates/angular/igx-ts/financial-chart/default/index.ts, templates/angular/igx-ts/linear-gauge/default/files/src/app/__path__/__name__.component.spec.ts, templates/angular/igx-ts/linear-gauge/default/files/src/app/__path__/__name__.component.ts, templates/angular/igx-ts/linear-gauge/default/index.ts, templates/angular/igx-ts/radial-gauge/default/files/src/app/__path__/__name__.component.spec.ts, templates/angular/igx-ts/radial-gauge/default/files/src/app/__path__/__name__.component.ts, templates/angular/igx-ts/radial-gauge/default/index.ts
Closes #644 .  
Chart packages were not properly installed due to npm concurrent installation. The specified package version in the template files are `~8.0.0` but the process was installing `^8.0.0` (so `8.2.12`, which changes the import paths).
=> fix(templates): update igniteui DV packages in angular templates

packages/cli/lib/PromptSession.ts, packages/cli/lib/commands/add.ts, packages/cli/lib/commands/new.ts
Removed the . from
"Read more at: https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/getting_started.html." which was resulting in a faulty link:
=> Removing unnecessary . in a link in a CLI warning message.

packages/igx-templates/igx-ts/carousel/default/files/src/app/__path__/__filePrefix__.component.scss
Closes #682 
The carousel's images were not displayed due to missing min-width of the parent container.
=> fix(carousel template, igx) images not displayed #682

packages/igx-templates/igx-ts/carousel/default/files/src/app/__path__/__filePrefix__.component.spec.ts
There is a failing test when executing _ig test_. It requires animations module.
=> Failing test - Add noop animations module 

packages/cli/migrations/migration-collection.json, packages/cli/migrations/update-5_0_0/index.spec.ts, packages/cli/migrations/update-5_0_0/index.ts, packages/igx-templates/igx-ts/projects/empty/files/src/app/app.module.ts, packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/app.module.ts, packages/igx-templates/igx-ts/projects/side-nav/files/src/app/app.module.ts
Airing on the safer side and adding the new HammerModule to project templates and old projects through migration. Related: https://github.com/IgniteUI/igniteui-angular/issues/6186
=> chore(igx-ts,migrations): add HammerModule

packages/core/util/FileSystem.ts, packages/core/util/Util.ts, packages/igx-templates/Update.spec.ts, packages/igx-templates/Update.ts, spec/unit/ProjectConfig-spec.ts, spec/unit/ts-transform/TypeScriptFileUpdate-spec.ts
Related to #723 .  
Command was not properly capturing all .ts files, only `*.component.ts`.
`FsFileSystem` implementation of `fileExists` and `directoryExists` was not correct and could throw.
=> fix(templates): upgrade command properly replaces strings in ALL .ts files

packages/igx-templates/igx-ts/projects/empty/index.ts
Related to changes for #617 .  
Project was getting generated with `"projectTemplate": "empty-project",` in the config, which may provide wrong info to other logic relying on it.
=> fix(igx,templates): correct empty proj template id

packages/igx-templates/Update.spec.ts, packages/igx-templates/Update.ts
When updating package.json dependencies w/ `@infragistics` scoped packages, ensure that the dependencies object has properly sorted keys.
=> fix(upgrade): sort packages.json dependencies when adding licensed package

packages/ng-schematics/package.json, packages/ng-schematics/src/migrations/migration-collection.json
Closes # .  
Despite having an `ng-update` in the package.json, `ng update` doesn't offer newer version of the package for update. Adding an empty collection as well, hopefully that'll trigger it to offer the update.
=> chore(schematics): add migratoins collection, update group

packages/cli/lib/commands/upgrade.ts, packages/ng-schematics/src/upgrade-packages/index.spec.ts, packages/ng-schematics/src/upgrade-packages/index.ts, spec/unit/upgrade-spec.ts
Related #723 and #727 
If the package template is not a recognized one (e.g. `ng-cli`), we provide the default template for that library (e.g. the first one)
=> fix(upgrade): provide default fallback for incorrect package template

packages/core/packages/PackageManager.ts, packages/core/util/Util.ts, spec/unit/packageManager-spec.ts
Co-authored-by: Damyan Petev <damyan.petev@gmail.com>
Closes #751.  
`npm install` fails to update package.json when there are other changes. When calling `queuePackage`, manually update package.json
=> fix(package-manager): manually update pckgJSON when adding packages

packages/igx-templates/igx-ts/custom-templates/fintech-grid/files/src/app/__path__/__filePrefix__.component.html, packages/igx-templates/igx-ts/custom-templates/fintech-grid/files/src/app/__path__/__filePrefix__.component.scss, packages/igx-templates/igx-ts/custom-templates/fintech-tree-grid/files/src/app/__path__/__filePrefix__.component.scss, packages/igx-templates/igx-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.component.scss, packages/igx-templates/igx-ts/projects/_base/files/src/styles.scss, packages/igx-templates/igx-ts/projects/side-nav/files/src/app/app.component.html, packages/igx-templates/igx-ts/projects/side-nav/files/src/app/app.component.scss, packages/igx-templates/igx-ts/projects/side-nav/files/src/app/app.component.ts
Closes # .  
Updated the padding for side-nav projects (no change for empty) so some views can override it and fill up the entire content. Especially for the dock manager, but also tried to tidy up the FinTech Grids a bit as well (dark enabled to show the diff):
=> Change igx nav proj padding and adjust dock manager/fintech views

packages/igx-templates/IgniteUIForAngularTemplate.ts, packages/igx-templates/Update.spec.ts, packages/igx-templates/igx-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.component.spec.ts, packages/igx-templates/igx-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.component.ts, packages/igx-templates/igx-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.module.ts, packages/igx-templates/igx-ts/dock-manager/default/index.ts, packages/igx-templates/package-resolve.spec.ts, packages/igx-templates/package-resolve.ts, packages/ng-schematics/src/cli-config/index.ts, packages/ng-schematics/src/utils/theme-import.ts, spec/unit/base-templates/IgniteUIForAngularTemplate-spec.ts
This allows dock manager template to be added after project packages
upgrade with correct package name without need for additional upgrade.
Closes # .  
=> fix(igx,dock-manager): resolve package name from project

packages/core/typescript/TypeScriptFileUpdate.ts, spec/unit/ts-transform/TypeScriptFileUpdate-spec.ts
Add the option for `TsFileUpdateUtil.AddRoute` to add route entries as children of an existing route path.
If `parentRoutePath` parameter (new, optional) is passed, the generated route entry will be added in the `children` array of the route matching the provided path.
=> feat(tsutil): add optional parent route to TsFileUpdateUtil.addRoute method

packages/igx-templates/igx-ts/dock-manager/default/index.ts
=> fix(dock-manager): Use correct module name in app.module import

packages/igx-templates/igx-ts/dock-manager/default/index.ts
=> fix(dock-manager): Use correct module name in app.module import #792

.vscode/launch.json, packages/cli/migrations/update-3_2/index.spec.ts, packages/cli/migrations/update-3_2/index.ts, packages/cli/migrations/update-4_2_3/index.spec.ts, packages/cli/migrations/update-4_2_3/index.ts, packages/cli/migrations/update-5_0_0/index.spec.ts, packages/cli/migrations/update-5_0_0/index.ts, packages/cli/migrations/update-5_0_3/index.spec.ts, packages/cli/migrations/update-5_0_3/index.ts, packages/cli/package.json, packages/core/package.json, packages/core/util/Schematics.ts, packages/ng-schematics/package.json, packages/ng-schematics/src/app-projects/index_spec.ts, packages/ng-schematics/src/cli-config/index.ts, packages/ng-schematics/src/cli-config/index_spec.ts, packages/ng-schematics/src/ng-new/index_spec.ts, packages/ng-schematics/src/tslint.json, packages/ng-schematics/src/utils/cli-config.ts, packages/ng-schematics/src/utils/theme-import.ts, yarn.lock
=> refator schematics workspace api

packages/igx-templates/igx-ts/autocomplete/autocomplete-extended/files/src/app/__path__/__filePrefix__.component.ts, packages/igx-templates/igx-ts/combo/default/files/src/app/__path__/__filePrefix__.component.ts, packages/igx-templates/igx-ts/combo/default/files/src/app/__path__/local-data.ts, packages/igx-templates/igx-ts/hierarchical-grid/hierarchical-grid-batch-editing/files/src/app/__path__/data.ts, packages/igx-templates/igx-ts/hierarchical-grid/hierarchical-grid-batch-editing/files/src/app/__path__/singer.ts, packages/igx-templates/igx-ts/linear-gauge/default/files/src/app/__path__/__filePrefix__.component.html, packages/igx-templates/igx-ts/list/default/files/src/app/__path__/__filePrefix__.component.html, packages/igx-templates/igx-ts/projects/_base/files/tsconfig.json
Add "compilerOptions.strict: true" to tsconfig.json.
Address some issues w/ `strictTemplates`.
Address some issues from strict typescript options.
Update `enhanced-autocomplete` to use `arr.reduce` instead of `arr.flat`, as `arr.flat` requires `es2019`, but default (in latest ng new proj) is `es2018`
=> fix(angular-templates): fix some issue with strict templates in igx-ts, add strict to tsconfig

packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/login-bar/login-bar.component.html
Logic drop-down was using `IgxDropDownItemComponent.index` property w/o implicitly setting it, causing a deprecation warning
=> fix(igx-ts): use explicit index in drop-down components for logic view

.vscode/tasks.json.old, packages/igx-templates/igx-ts/custom-templates/fintech-grid/files/src/app/__path__/__filePrefix__.component.html, packages/igx-templates/igx-ts/custom-templates/fintech-tree-grid/files/src/app/__path__/__filePrefix__.component.html, packages/igx-templates/igx-ts/custom-templates/weather-forecast/files/src/app/__path__/__filePrefix__.component.html, packages/igx-templates/igx-ts/custom-templates/weather-forecast/files/src/app/__path__/__filePrefix__.component.scss, packages/igx-templates/igx-ts/grid/grid-custom/files/src/app/__path__/__filePrefix__.component.html
Some icons were using the deprecated 'color' property
Rename referance from `cell.row.rowData` => `cell.row.data`
=> fix(igx-ts): remove deprecated properties from scenario templates

packages/ng-schematics/src/component/schema.json, packages/ng-schematics/src/ng-new/schema.json, packages/ng-schematics/src/upgrade-packages/schema.json
Fixing an error shown when executing `ng g @igniteui/angular-schematics:c` in a project.
=> fix(schematics): resolve schema id deprecation warning

packages/cli/templates/webcomponents/igc-ts/projects/empty/files/index.html, packages/cli/templates/webcomponents/igc-ts/projects/empty/files/src/app.ts
Making the NavDrawer component an HTMLElement instead of lit-element so that the global theme can make it through the shadow dom.
=> NavDrawer view is now HTMLElement instead of lit

packages/cli/templates/webcomponents/igc-ts/projects/empty/files/package.json
Until CLI is compatible with TypeScript 4.5.x we need to stick to 4.4.x
=> chore: only patch updates for typescript

packages/cli/templates/webcomponents/igc-ts/grid/grid-editing/files/src/app/__path__/DataGridSharedData.ts, packages/cli/templates/webcomponents/igc-ts/grid/grid-editing/files/src/app/__path__/__filePrefix__.ts, packages/cli/templates/webcomponents/igc-ts/grid/grid-summaries/files/src/app/__path__/DataGridSharedData.ts, packages/cli/templates/webcomponents/igc-ts/grid/grid-summaries/files/src/app/__path__/__filePrefix__.ts, packages/cli/templates/webcomponents/igc-ts/projects/empty/files/src/app.ts, packages/cli/templates/webcomponents/igc-ts/projects/empty/files/src/index.ts
=> Fixing some lint errors in grid views

packages/igx-templates/igx-ts/custom-templates/fintech-grid/files/src/app/__path__/__filePrefix__.component.scss
Closes #1020 
Removed `@include theme($default-palette);` from the template because it was slowing down the performance of the grid.
=> fix(fintech grid): fix slow grid #1020

packages/ng-schematics/src/utils/theme-import.ts
After testing we found a problem where the `@use` wasn't at the beginning of the file and `as *` was also missing.
=> refactor(theme-import): Place sass/scss imports before content.

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/styles.css
height: 100% is not needed in generated CodeGen WC projects but it breaks some layouts (scrollbars are displayed in Team Collaboration app, for example).
=> Remove height: 100% from body

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/.npmrc
This PR adds `.npmrc` file to webcomponents' base project template.
=> Add .npmrc to wc proj template

packages/igx-templates/igx-ts/projects/_base/files/package.json, packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json
From time to time `igniteui-theming`, which is a peer dependency of `igniteui-angular`, is not installed on a root level in the generated project and the following error is thrown:
```console
./src/styles.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
╷
1 │ @use 'igniteui-theming/sass/color/functions' as *;
│ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
node_modules\@infragistics\igniteui-angular\lib\core\styles\base\_mixins.scss 1:1  @forward
node_modules\@infragistics\igniteui-angular\lib\core\styles\base\_index.scss 2:1   @use
node_modules\@infragistics\igniteui-angular\lib\core\styles\themes\_core.scss 6:1  @forward
@infragistics\igniteui-angular\_index.scss 1:1 …
```
=> chore(igx): add explicitely igniteui-theming package

packages/cli/templates/webcomponents/igc-ts/projects/_base_with_home/files/package.json
When building our webComponent app, which uses charts, there is a critical memory allocation problem with rollup under Linux. The build process would fail with the error message: "FATAL ERROR: Reached heap limit. Allocation failed - JavaScript heap out of memory." This issue was unique to Linux because the default Node.js heap size is limited to 2GB, while the build succeeds under Windows, where the default Node.js heap size is 4GB.
Closes # .  
=> Fix memory allocation issue during build of webComponent app that uses igc-category-chart

CHANGELOG.md, packages/cli/package.json, packages/core/package.json, packages/igx-templates/package.json, packages/ng-schematics/package.json
Remove ng update package groups, because they contain product libraries, `igniteui-angular` and its licensed version, which will lead to the latter being omitted in the `ng update` list.
Along with the [following change](https://github.com/IgniteUI/igniteui-angular/pull/13512) in the `igniteui-angular`, when the latter is updated then `igniteui-angular-i18n` will also be updated and when `ng update` is invoked then `igniteui-angular` will be visible as a name of the group.
=> chore(migrations): remove ng update package groups

CHANGELOG.md, packages/cli/package.json, packages/core/package.json, packages/core/util/Util.ts, packages/igx-templates/package.json, packages/ng-schematics/package.json, spec/acceptance/new-spec.ts
Closes #1170 .  
Update `Utils.LowerDashed` function. It will now add dashes:
- on the place of empty spaces.
- between lower and upper case letters.
- between lower case letter and number.
=> fix: update Utils.LowerDashed function

packages/cli/package.json, packages/core/package.json, packages/core/util/Util.ts, packages/igx-templates/package.json, packages/ng-schematics/package.json
Closes #1171 
Do not add dash before numbers. `lowerDashed` will now add dash between lower-case letter or number and upper-case letter as well as on the place of the empty spaces.
=> In lowerDashed do not add dash before numbers - 12.0.x

packages/core/util/Util.ts
Closes #1171 
Do not add dash before numbers. `lowerDashed` will now add dash between lower-case letter or number and upper-case letter as well as on the place of the empty spaces.
=> In lowerDashed do not add dash before numbers - 13.0.x

packages/core/util/Util.ts
Closes #1171 
Do not add dash before numbers. `lowerDashed` will now add dash between lower-case letter or number and upper-case letter as well as on the place of the empty spaces.
=> In lowerDashed do not add dash before numbers

CHANGELOG.md, packages/cli/package.json, packages/core/package.json, packages/igx-templates/igx-ts-legacy/projects/_base/files/package.json, packages/igx-templates/package.json, packages/ng-schematics/package.json, packages/ng-schematics/src/ng-new/index.ts, packages/ng-schematics/src/ng-new/index_spec.ts, packages/ng-schematics/src/ng-new/schema.json, packages/ng-schematics/src/ng-new/schema.ts, packages/ng-schematics/src/prompt/SchematicsPromptSession.ts
With the introduction of standalone components in our CLI the ng-schematics need to be able to resolve the type of the project when calling `ng new`. So far, we've only had one project library for angular - `igx-ts`, though now we have two - `igx-ts` & `igx-ts-legacy`. This creates the need to add the `--type` flag which will default to `igx-ts` and when calling `ng new` this will allow our schematics to not initiate a prompt session.
=> Resolve proj lib by  type

packages/cli/package.json, packages/core/package.json, packages/core/typescript/TypeScriptFileUpdate.ts, packages/igx-templates/package.json, packages/ng-schematics/package.json
This PR adds the ability to generate lazy loaded routes with the TSFile update for Angular.
=> Lazy load routes

packages/igx-templates/igx-ts-legacy/projects/_base/files/ignite-ui-cli.json, packages/igx-templates/igx-ts/projects/_base/files/src/app/app.config.ts
Adds the `provideHttpClient` method in the `providers` array for projects with standalone components.
Also sets the project type of legacy angular projects to `igx-ts-legacy` in the cli config.
=> Provide http client

packages/cli/templates/react/igr-ts/bullet-graph/default/files/src/app/__path__/__filePrefix__.test.tsx, packages/cli/templates/react/igr-ts/category-chart/default/files/src/app/__path__/__filePrefix__.test.tsx, packages/cli/templates/react/igr-ts/doughnut-chart/default/files/src/app/__path__/__filePrefix__.test.tsx, packages/cli/templates/react/igr-ts/financial-chart/default/files/src/app/__path__/__filePrefix__.test.tsx, packages/cli/templates/react/igr-ts/grid/basic/files/src/app/__path__/__filePrefix__.test.tsx, packages/cli/templates/react/igr-ts/linear-gauge/default/files/src/app/__path__/__filePrefix__.test.tsx, packages/cli/templates/react/igr-ts/pie-chart/default/files/src/app/__path__/__filePrefix__.test.tsx, packages/cli/templates/react/igr-ts/radial-gauge/default/files/src/app/__path__/__filePrefix__.test.tsx
Closes #1220 .  
Fixed grid and all other available templates to use `from './$(path)'` instead of the `'from ./index'`.
=> fix(Imports): Fixed class import path in .test.ts

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/package.json, packages/cli/templates/webcomponents/igc-ts/projects/_base_with_home/files/package.json
Closes #1256
The error is still shown but for a very brief moment this time:
=> chore(webc): Bump the version of @web/dev-server in the WebC templates

packages/cli/package.json, packages/core/package.json, packages/core/types/TemplateDependency.ts, packages/core/typescript/TypeScriptFileUpdate.ts, packages/igx-templates/package.json, packages/ng-schematics/package.json
This PR allows the TSFU to add a schemas member to the `@NgModule` or `@Component` decorators in Angular.
=> Adding schema to template dependency 13.2.x

packages/core/types/TemplateDependency.ts, packages/core/typescript/TypeScriptFileUpdate.ts
This PR allows the TSFU to add a `schemas` member to the `@NgModule` or `@Component` decorators in `Angular`.
=> Adding schema to template dependency 13.4.x

packages/core/types/TemplateDependency.ts, packages/core/typescript/TypeScriptFileUpdate.ts
This PR allows the TSFU to add a schemas member to the `@NgModule` or `@Component` decorators in Angular.
Related:
https://github.com/IgniteUI/igniteui-cli/pull/1270
https://github.com/IgniteUI/igniteui-cli/pull/1278
https://github.com/IgniteUI/igniteui-cli/pull/1279
=> Adding schema to template dependency

packages/cli/lib/templates/IgniteUIForReactTemplate.ts, packages/cli/package.json, packages/cli/templates/react/ReactTypeScriptFileUpdate.ts, packages/cli/templates/react/types/ReactRouteEntry.ts, packages/cli/templates/react/types/ReactRouteLike.ts, packages/cli/templates/react/types/ReactRouteTarget.ts, packages/cli/templates/react/types/index.ts, packages/core/package.json, packages/core/typescript/TypeScriptFileUpdate.ts, packages/core/util/GlobalConstants.ts, packages/igx-templates/package.json, packages/ng-schematics/package.json, spec/unit/ts-transform/ReactTypeScriptFileUpdate-spec.ts
Closes [#30403](https://infragistics.visualstudio.com/Indigo_Platform/_workitems/edit/30403)
The `ReactTypeScriptFileUpdate` overrides `addRoute` and `buildRouteStructure` of the `TypeScriptFileUpdate` to provide platform-specific behavior when trying to add routes supported by the `react-router-dom` package. 
For more info, refer to - [AngularTypeScriptFileUpdate PR](https://github.com/IgniteUI/igniteui-cli/pull/1243) as the two share the same base and expose the same API.
=> Refactor the ReactTypeScriptFileUpdate

packages/igx-templates/igx-ts/projects/_base/files/package.json
=> Adding 'ng lint' command in Angular Standalone templates 13.2

packages/igx-templates/igx-ts/projects/_base/files/package.json
=> Adding 'ng lint' command in Angular Standalone templates 13.4

packages/igx-templates/igx-ts/projects/_base/index.ts
Closes https://github.com/IgniteUI/igniteui-cli/issues/1319
This PR adds a missing `igxPackage` property in the config of the `base` template for the `igx-ts` project type i.e. projects that are based on Angular with standalone components.
Testing this should be done by running the wizard and ensuring that `igniteui-angular` exists in the `app.config.ts` when no license is applied and `@infragistics/igniteui-angular` exists when licensing is applied.
=> Provide default package name in config for igx-ts projects

packages/igx-templates/igx-ts-legacy/projects/_base/files/tsconfig.json
The `skipLibCheck` property is also defined in the standalone templates.
The problem was caught in the CodeGen angular module generated project, where there was a problem with the `igniteui-webcomponents` library (which is used by `igniteui-angular`, because the of the wc rating). `igniteui-webcomponents` is using `typescript@5.6`. while `igniteui-angular` is using `typescript@5.5` and the following error is shown:
```console
Error: node_modules/igniteui-webcomponents/components/icon/registry/default-map.d.ts:10:16 - error TS2552: Cannot find name 'MapIterator'. Did you mean 'Iterator'?        
10     entries(): MapIterator<[T, U]>;
~~~~~~~~~~~
```
This is a Typescript API change from 5.5 to 5.6 and because the problem is not related to the generated angular project and it is running …
=> fix(ng): use "skipLibCheck": true for legacy igx projects

packages/cli/templates/webcomponents/igc-ts/grid/grid-editing/files/src/app/__path__/DataGridSharedData.ts, packages/core/packages/PackageManager.ts, packages/core/util/Util.ts, spec/acceptance/help-spec.ts, spec/unit/new-spec.ts, spec/unit/packageManager-spec.ts
Resolve Vulnerability alerts in the igniteui-cli
Code scanning alerts fixes:
- Dismiss the insecure randomness alerts because this is only used for dummy data, and there is no need for security in this case.
- Replace execSync with spawnSync to avoid constructing the shell command by concatenating strings with untrusted input.
- Add check to ensure that the function does not allow merging of special properties like proto and constructor.
=> resolve code scanning vulnerability alerts

packages/cli/templates/react/igr-ts/projects/_base/files/vite.config.ts
Removing 'define' from vite.config. 
This configuration tells Vite to replace all instances of `global` with `window` in the code before building the project. It's essentially a straightforward text replacement or string substitution mechanism. Any occurrence of the word `global` in the code will be replaced with `window`, regardless of the context. This means if the project have variables, function names, or anything else that contains `global` as a substring (like `globalView`, `isGlobalEnabled`), these will also be replaced.
=> Removing global replacement.

packages/core/types/FileSystem.ts, packages/core/update/Update.ts, packages/ng-schematics/package.json, packages/ng-schematics/src/upgrade-packages/index.ts, packages/ng-schematics/src/utils/NgFileSystem.ts, yarn.lock
Closes https://github.com/IgniteUI/igniteui-cli/issues/1298
This PR modifies the `NgFileSystem`'s `glob` function to expect multiple ignore patterns. It then loops through the contents of the root directory and its subdirectories, ignoring all entries that match any of the provided patterns and collects only the entries that match the expected pattern. Angular's file visitor is used only if no ignore patterns are provided. Additionally, when upgrading packages, the `dist` folder is now also ignored.
Currently the `@igniteui/angular-schematics:upgrade-packages` schematic will fail for projects that have not defined an `ignite-ui-cli.json` config file. The reason is that, at runtime, the schematic will attempt to infer the project's …
=> Fix pattern matching when upgrading packages

packages/cli/package.json, packages/core/package.json, packages/igx-templates/igx-ts-legacy/projects/_base/files/__dot__eslintrc.json, packages/igx-templates/igx-ts-legacy/projects/_base/files/__dot__github/workflows/github-pages.yml, packages/igx-templates/igx-ts-legacy/projects/_base_with_home/files/__dot__github/workflows/github-pages.yml, packages/igx-templates/package.json, packages/ng-schematics/package.json
Disable standalone lint check for angular modules and fix paths in github pages yaml files for angular modules.
=> Disable standalone lint check and fix paths for angular modules

packages/cli/templates/react/igr-ts/projects/_base/files/__dot__github/workflows/github-pages.yml, packages/cli/templates/webcomponents/igc-ts/projects/_base/files/__dot__github/workflows/github-pages.yml, packages/igx-templates/igx-ts-legacy/projects/_base/files/__dot__github/workflows/github-pages.yml, packages/igx-templates/igx-ts-legacy/projects/_base_with_home/files/__dot__github/workflows/github-pages.yml, packages/igx-templates/igx-ts/projects/_base/files/__dot__github/workflows/github-pages.yml, packages/igx-templates/igx-ts/projects/_base_with_home/files/__dot__github/workflows/github-pages.yml
Upgrade versions of deploy-pages and upload-pages artifact in github pages workflow file for angular, react and web-components.
=> Upgrade github pages deploy and artifact versions

packages/cli/templates/webcomponents/igc-ts/projects/_base/files/vite.config.ts
Increase maximum file size to cache in webComponents's vite configuration to 10 MB
=> feat: increase maximum file size to cache in webComponents's vite configuration to 10 MB

packages/igx-templates/igx-ts-legacy/projects/_base/files/package.json, packages/igx-templates/igx-ts/projects/_base/files/package.json
Add overrides for  "@angular/core": "^19.0.0" and "@angular/common": "^19.0.0" for reveal-sdk-wrappers-angular
=> fix: add overrides for reveal sdk wrappers

packages/core/update/Update.ts, spec/unit/update-spec.ts
=> fix(WC): update themes import paths to licensed version

packages/cli/package.json, packages/cli/templates/webcomponents/igc-ts/projects/_base/files/__dot__github/workflows/github-pages.yml, packages/cli/templates/webcomponents/igc-ts/projects/_base/files/package.json, packages/cli/templates/webcomponents/igc-ts/projects/_base/files/src/app/models/css.d.ts, packages/cli/templates/webcomponents/igc-ts/projects/_base/files/vite.config.ts, packages/core/package.json, packages/igx-templates/package.json, packages/ng-schematics/package.json
Remove the step in github pages yml for adding the ig-theme, because we’ll use the import inline css syntax for the styles. The changes will be handled in the CodeGen, so no further modifications are needed here.
=> fix: add missing static css files for WC
